In [1]:
import pandas as pd

In [2]:
df = pd.read_hdf('C:\\Users\\Administrator\\Desktop\\\mergehsi\\his_simplified.h5')
df

,instrument,type,month,trade_date,trade_time,price,vol
b'trade_datetime',,,,,,,
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,8
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,11
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,10
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,26
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,3
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,3
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,4
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,13
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,3
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,3
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,3
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,2
2014-01-02 09:14:00,HSI,F,1401,2014-01-02,09:14:00,23414.0,1
...,...,...,...,...,...,...,...
2015-11-30 16:14:55,HSI,F,1512,2015-11-30,16:14:55,21915.0,1
2015-11-30 16:14:55,HSI,F,1512,2015-11-30,16:14:55,21910.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21912.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21911.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21908.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21908.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21908.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21914.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21915.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21908.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,3
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,4
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21915.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21909.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21909.0,1
2015-11-30 16:14:59,HSI,F,1512,2015-11-30,16:14:59,21909.0,1
2015-11-30 16:14:59,HSI,F,1512,2015-11-30,16:14:59,21909.0,1

In [13]:
df.index.rename('trade_datetime', inplace = True)
df.index

DatetimeIndex(['2014-01-02 09:14:00', '2014-01-02 09:14:00',
               '2014-01-02 09:14:00', '2014-01-02 09:14:00',
               '2014-01-02 09:14:00', '2014-01-02 09:14:00',
               '2014-01-02 09:14:00', '2014-01-02 09:14:00',
               '2014-01-02 09:14:00', '2014-01-02 09:14:00',
               ...
               '2015-11-30 16:14:58', '2015-11-30 16:14:58',
               '2015-11-30 16:14:58', '2015-11-30 16:14:58',
               '2015-11-30 16:14:58', '2015-11-30 16:14:58',
               '2015-11-30 16:14:58', '2015-11-30 16:14:58',
               '2015-11-30 16:14:59', '2015-11-30 16:14:59'],
              dtype='datetime64[ns]', name='trade_datetime', length=22925593, freq=None)

In [5]:
df2.index

DatetimeIndex(['2013-05-02 09:14:00', '2013-05-02 09:14:00',
               '2013-05-02 09:14:00', '2013-05-02 09:14:00',
               '2013-05-02 09:14:00', '2013-05-02 09:14:00',
               '2013-05-02 09:14:00', '2013-05-02 09:14:00',
               '2013-05-02 09:14:00', '2013-05-02 09:14:00',
               ...
               '2013-12-31 11:59:58', '2013-12-31 11:59:58',
               '2013-12-31 11:59:58', '2013-12-31 11:59:58',
               '2013-12-31 11:59:58', '2013-12-31 11:59:58',
               '2013-12-31 11:59:59', '2013-12-31 11:59:59',
               '2013-12-31 11:59:59', '2013-12-31 11:59:59'],
              dtype='datetime64[ns]', name='trade_datetime', length=7859462, freq=None)

In [3]:
df2 = pd.read_hdf('C:\\Users\\Administrator\\Desktop\\\mergehsi\\his_simplified2.h5')
df2

,instrument,type,month,trade_date,trade_time,price,vol
trade_datetime,,,,,,,
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,3.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,45.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,2.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,3.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,3.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,7.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,14.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,10.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,3.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,10.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,2.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,2.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,4.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,3.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,2.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,2.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,7.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
2013-05-02 09:14:00,HSI,F,1305.0,2013-05-02,09:14:00,22574.0,1.0
...,...,...,...,...,...,...,...
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23321.0,9.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23321.0,4.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23321.0,1.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23321.0,2.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23331.0,1.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23331.0,1.0
2013-12-31 11:59:55,HSI,F,1401.0,2013-12-31,11:59:55,23324.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23325.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23336.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23336.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23327.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23332.0,3.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23323.0,1.0
2013-12-31 11:59:56,HSI,F,1401.0,2013-12-31,11:59:56,23320.0,1.0
2013-12-31 11:59:57,HSI,F,1401.0,2013-12-31,11:59:57,23329.0,1.0
2013-12-31 11:59:57,HSI,F,1401.0,2013-12-31,11:59:57,23332.0,1.0
2013-12-31 11:59:57,HSI,F,1401.0,2013-12-31,11:59:57,23334.0,1.0
2013-12-31 11:59:57,HSI,F,1401.0,2013-12-31,11:59:57,23335.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23329.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23329.0,5.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23333.0,4.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23335.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23336.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23336.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23336.0,1.0
2013-12-31 11:59:58,HSI,F,1401.0,2013-12-31,11:59:58,23333.0,1.0
2013-12-31 11:59:59,HSI,F,1401.0,2013-12-31,11:59:59,23336.0,1.0
2013-12-31 11:59:59,HSI,F,1401.0,2013-12-31,11:59:59,23336.0,1.0
2013-12-31 11:59:59,HSI,F,1401.0,2013-12-31,11:59:59,23334.0,1.0
2013-12-31 11:59:59,HSI,F,1401.0,2013-12-31,11:59:59,23333.0,4.0

In [14]:
df2.month.astype(int)

trade_datetime
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
2013-05-02 09:14:00    1305
                       ...
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:55    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:56    1401
2013-12-31 11:59:57    1401
2013-12-31 11:59:57    1401
2013-12-31 11:59:57    1401
2013-12-31 11:59:57    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:58    1401
2013-12-31 11:59:59    1401
2013-12-31 11:59:59    1401
2013-12-31 11:59:59    1401
2013-12-31 11:59:59    1401
Name: month, Length: 7859462, dtype: int32

In [16]:
df2.month = df2.month.astype(int)

In [19]:
df2.vol = df2.vol.astype(int)
df2

,instrument,type,month,trade_date,trade_time,price,vol
trade_datetime,,,,,,,
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,45
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,7
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,14
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,10
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,10
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,4
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,7
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
...,...,...,...,...,...,...,...
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23321.0,9
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23321.0,4
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23321.0,1
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23321.0,2
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23331.0,1
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23331.0,1
2013-12-31 11:59:55,HSI,F,1401,2013-12-31,11:59:55,23324.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23325.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23336.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23336.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23327.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23332.0,3
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23323.0,1
2013-12-31 11:59:56,HSI,F,1401,2013-12-31,11:59:56,23320.0,1
2013-12-31 11:59:57,HSI,F,1401,2013-12-31,11:59:57,23329.0,1
2013-12-31 11:59:57,HSI,F,1401,2013-12-31,11:59:57,23332.0,1
2013-12-31 11:59:57,HSI,F,1401,2013-12-31,11:59:57,23334.0,1
2013-12-31 11:59:57,HSI,F,1401,2013-12-31,11:59:57,23335.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23329.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23329.0,5
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23333.0,4
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23335.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23336.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23336.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23336.0,1
2013-12-31 11:59:58,HSI,F,1401,2013-12-31,11:59:58,23333.0,1
2013-12-31 11:59:59,HSI,F,1401,2013-12-31,11:59:59,23336.0,1
2013-12-31 11:59:59,HSI,F,1401,2013-12-31,11:59:59,23336.0,1
2013-12-31 11:59:59,HSI,F,1401,2013-12-31,11:59:59,23334.0,1
2013-12-31 11:59:59,HSI,F,1401,2013-12-31,11:59:59,23333.0,4

In [20]:
df3 = df2.append(df)

In [21]:
df3

,instrument,type,month,trade_date,trade_time,price,vol
trade_datetime,,,,,,,
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,45
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,7
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,14
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,10
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,10
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,4
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,3
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,2
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,7
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
2013-05-02 09:14:00,HSI,F,1305,2013-05-02,09:14:00,22574.0,1
...,...,...,...,...,...,...,...
2015-11-30 16:14:55,HSI,F,1512,2015-11-30,16:14:55,21915.0,1
2015-11-30 16:14:55,HSI,F,1512,2015-11-30,16:14:55,21910.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21912.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21915.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21911.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21909.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21908.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:56,HSI,F,1512,2015-11-30,16:14:56,21907.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21908.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21908.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21914.0,1
2015-11-30 16:14:57,HSI,F,1512,2015-11-30,16:14:57,21915.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21908.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,3
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,1
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21907.0,4
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21915.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21909.0,2
2015-11-30 16:14:58,HSI,F,1512,2015-11-30,16:14:58,21909.0,1
2015-11-30 16:14:59,HSI,F,1512,2015-11-30,16:14:59,21909.0,1
2015-11-30 16:14:59,HSI,F,1512,2015-11-30,16:14:59,21909.0,1

In [ ]:
df3.to_hdf('merge_HSI','hsi')