In [2]:
import pandas as pd
df = pd.read_hdf('C:\\Users\\Administrator\\Desktop\\Work\\data\\hsi_account\\account_data_sumprofit.h5')
df

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:05,A0002,HSIK3,2,22565.0,2013-05-02 09:15:05.000,22461.0,2013-05-02 09:32:49.000,104.0,104.0
2013-05-02 09:15:12,A0003,HSIK3,2,22560.0,2013-05-02 09:15:12.000,22549.0,2013-05-02 09:27:56.000,11.0,11.0
2013-05-02 09:15:53,A0004,HSIK3,2,22554.0,2013-05-02 09:15:53.000,22529.0,2013-05-02 09:16:26.000,25.0,25.0
2013-05-02 09:15:55,A0005,HSIK3,1,22553.0,2013-05-02 09:15:55.000,22526.0,2013-05-02 09:19:00.000,-27.0,-27.0
2013-05-02 09:16:21,A0001,HSIK3,2,22524.0,2013-05-02 09:16:21.000,22420.0,2013-05-02 09:35:12.000,104.0,104.0
2013-05-02 09:17:08,A0006,HSIK3,1,22535.0,2013-05-02 09:17:08.000,22563.0,2013-05-02 09:23:30.000,28.0,28.0
2013-05-02 09:18:56,A0007,HSIK3,1,22528.0,2013-05-02 09:18:56.000,22548.0,2013-05-02 09:26:14.000,20.0,20.0
2013-05-02 09:19:49,A0008,HSIK3,2,22527.0,2013-05-02 09:19:49.000,22421.0,2013-05-02 09:35:15.000,106.0,106.0
2013-05-02 09:22:39,A0004,HSIK3,2,22513.0,2013-05-02 09:22:39.000,22555.0,2013-05-02 09:23:16.000,-42.0,-17.0
2013-05-02 09:22:47,A0009,HSIK3,2,22515.0,2013-05-02 09:22:47.000,22562.0,2013-05-02 09:23:23.000,-47.0,-47.0
2013-05-02 09:23:07,A0010,HSIK3,1,22540.0,2013-05-02 09:23:07.000,22555.0,2013-05-02 09:25:44.000,15.0,15.0
2013-05-02 09:24:09,A0009,HSIK3,2,22552.0,2013-05-02 09:24:09.000,22539.0,2013-05-02 09:24:40.000,13.0,-34.0
2013-05-02 09:24:45,A0011,HSIK3,2,22543.0,2013-05-02 09:24:45.000,22540.0,2013-05-02 09:29:48.000,3.0,3.0
2013-05-02 09:25:00,A0012,HSIK3,2,22549.0,2013-05-02 09:25:00.000,22445.0,2013-05-02 09:33:02.000,104.0,104.0
2013-05-02 09:26:24,A0007,HSIK3,1,22542.0,2013-05-02 09:26:24.000,22495.0,2013-05-02 09:32:36.000,-47.0,-27.0
2013-05-02 09:29:04,A0004,HSIK3,2,22538.0,2013-05-02 09:29:04.000,22528.0,2013-05-02 09:30:47.000,10.0,-7.0
2013-05-02 09:30:16,A0009,HSIK3,2,22514.0,2013-05-02 09:30:16.000,22443.0,2013-05-02 09:33:16.000,71.0,37.0
2013-05-02 09:30:30,A0006,HSIK3,1,22534.0,2013-05-02 09:30:30.000,22487.0,2013-05-02 09:32:39.000,-47.0,-19.0
2013-05-02 09:31:06,A0003,HSIK3,2,22510.0,2013-05-02 09:31:06.000,22452.0,2013-05-02 09:32:57.000,58.0,69.0
2013-05-02 09:31:25,A0004,HSIK3,2,22508.0,2013-05-02 09:31:25.000,22499.0,2013-05-02 09:32:00.000,9.0,2.0
2013-05-02 09:32:51,A0004,HSIK3,2,22451.0,2013-05-02 09:32:51.000,22434.0,2013-05-02 09:33:35.000,17.0,19.0
2013-05-02 09:33:04,A0007,HSIK3,1,22442.0,2013-05-02 09:33:04.000,22490.0,2013-05-02 09:41:04.000,48.0,21.0
2013-05-02 09:33:16,A0006,HSIK3,1,22442.0,2013-05-02 09:33:16.000,22470.0,2013-05-02 09:36:23.000,28.0,9.0
2013-05-02 09:35:23,A0013,HSIK3,1,22425.0,2013-05-02 09:35:23.000,22459.0,2013-05-02 09:35:57.000,34.0,34.0
2013-05-02 09:35:34,A0006,HSIK3,1,22432.0,2013-05-02 09:35:34.000,22460.0,2013-05-02 09:36:12.000,28.0,37.0
2013-05-02 09:36:08,A0001,HSIK3,2,22457.0,2013-05-02 09:36:08.000,22451.0,2013-05-02 09:48:12.000,6.0,110.0
2013-05-02 09:37:18,A0012,HSIK3,1,22472.0,2013-05-02 09:37:18.000,22481.0,2013-05-02 09:43:45.000,9.0,113.0
2013-05-02 09:37:19,A0010,HSIK3,1,22472.0,2013-05-02 09:37:19.000,22518.0,2013-05-02 10:15:28.000,46.0,61.0
2013-05-02 09:38:03,A0002,HSIK3,2,22476.0,2013-05-02 09:38:03.000,22461.0,2013-05-02 09:38:38.000,15.0,119.0
2013-05-02 09:39:46,A0001,HSIK3,2,22481.0,2013-05-02 09:39:46.000,22453.0,2013-05-02 09:46:17.000,28.0,138.0
...,...,...,...,...,...,...,...,...,...
2015-12-30 15:37:27,A1247,HSIF6,1,21910.0,2015-12-30 15:37:27.000,21918.0,2015-12-30 15:43:50.000,8.0,-1992.0
2015-12-30 15:37:54,A1537,HSIF6,1,21908.0,2015-12-30 15:37:54.000,21916.0,2015-12-30 15:53:51.000,8.0,236.0
2015-12-30 15:39:08,A0775,HSIF6,2,21912.0,2015-12-30 15:39:08.000,21905.0,2015-12-30 15:40:03.000,7.0,13218.0
2015-12-30 15:39:14,A0877,HSIF6,1,21916.0,2015-12-30 15:39:14.000,21925.0,2015-12-30 15:54:27.000,9.0,4898.0
2015-12-30 15:39:24,A1630,HSIF6,1,21914.0,2015-12-30 15:39:24.000,21918.0,2015-12-30 15:54:06.000,4.0,47.0
2015-12-30 15:40:09,A1502,HSIF6,1,21905.0,2015-12-30 15:40:09.000,21915.0,2015-12-30 15:42:09.000,10.0,283.0
2015-12-30 15:40:42,A0025,HSIF6,1,21907.0,2015-12-30 15:40:42.000,21915.0,2015-12-30 15:44:37.000,8.0,570.0
2015-12-30 15:40:58,A1207,HSIF6,2,21910.0,2015-12-30 15:40:58.000,21902.0,2015-12-30 16:09:35.000,8.0,360.0
2015-12-30 15:44:52,A1583,HSIF6,2,21912.0,2015-12-30 15:44:52.000,21922.0,2015-12-30 15:54:42.000,-10.0,-110.0
2015-12-30 15:45:11,A1502,HSIF6,1,21907.0,2015-12-30 15:45:11.000,21917.0,2015-12-30 15:52:37.000,10.0,293.0
2015-12-30 15:45:33,A1381,HSIF6,1,21910.0,2015-12-30 15:45:33.000,21902.0,2015-12-30 15:48:34.000,-8.0,1766.0
2015-12-30 15:45:47,A0025,HSIF6,1,21910.0,2015-12-30 15:45:47.000,21928.0,2015-12-30 15:55:54.000,18.0,588.0
2015-12-30 15:46:34,A1502,HSIF6,1,21909.0,2015-12-30 15:46:34.000,21917.0,2015-12-30 15:53:47.000,8.0,301.0
2015-12-30 15:48:11,A0184,HSIF6,1,21905.0,2015-12-30 15:48:11.000,21915.0,2015-12-30 15:52:49.000,10.0,-922.0
2015-12-30 15:48:19,A1502,HSIF6,1,21898.0,2015-12-30 15:48:19.000,21902.0,2015-12-30 15:49:12.000,4.0,305.0
2015-12-30 15:50:32,A1502,HSIF6,1,21900.0,2015-12-30 15:50:32.000,21910.0,2015-12-30 15:51:28.000,10.0,315.0
2015-12-30 15:51:13,A1381,HSIF6,2,21905.0,2015-12-30 15:51:13.000,21910.0,2015-12-30 15:52:22.000,-5.0,1761.0
2015-12-30 15:52:10,A1247,HSIF6,1,21911.0,2015-12-30 15:52:10.000,21915.0,2015-12-30 15:52:49.000,4.0,-1988.0
2015-12-30 15:52:42,A1058,HSIF6,1,21916.0,2015-12-30 15:52:42.000,21925.0,2015-12-30 15:54:55.000,9.0,38.0
2015-12-30 15:52:57,A1600,HSIF6,1,21914.0,2015-12-30 15:52:57.000,21924.0,2015-12-30 15:54:49.000,10.0,91.0
2015-12-30 15:53:05,A1516,HSIF6,1,21915.0,2015-12-30 15:53:05.000,21924.0,2015-12-30 15:54:53.000,9.0,825.0
2015-12-30 15:56:14,A1630,HSIF6,1,21931.0,2015-12-30 15:56:14.000,21894.0,2015-12-30 15:59:49.000,-37.0,10.0
2015-12-30 15:56:51,A0481,HSIF6,1,21930.0,2015-12-30 15:56:51.000,21895.0,2015-12-30 15:59:45.000,-35.0,1087.0
2015-12-30 15:57:40,A0481,HSIF6,1,21930.0,2015-12-30 15:57:40.000,21910.0,2015-12-30 16:00:09.000,-20.0,1067.0
2015-12-30 15:58:29,A1256,HSIF6,2,21924.0,2015-12-30 15:58:29.000,21916.0,2015-12-30 15:59:04.000,8.0,-376.0
2015-12-30 15:58:41,A0305,HSIF6,2,21921.0,2015-12-30 15:58:41.000,21910.0,2015-12-30 16:04:38.000,11.0,-1807.0
2015-12-30 15:59:19,A0231,HSIF6,2,21908.0,2015-12-30 15:59:19.000,21902.0,2015-12-30 16:05:07.000,6.0,-2373.0
2015-12-30 15:59:20,A0025,HSIF6,1,21907.0,2015-12-30 15:59:20.000,21918.0,2015-12-30 16:00:25.000,11.0,599.0
2015-12-30 15:59:28,A0305,HSIF6,2,21912.0,2015-12-30 15:59:28.000,21901.0,2015-12-30 16:05:43.000,11.0,-1796.0
2015-12-30 16:08:16,A1116,HSIF6,1,21902.0,2015-12-30 16:08:16.000,21909.0,2015-12-30 16:13:51.000,7.0,3938.0

In [3]:
df2 = df['2013-05-02']

In [4]:
df2

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:05,A0002,HSIK3,2,22565.0,2013-05-02 09:15:05.000,22461.0,2013-05-02 09:32:49.000,104.0,104.0
2013-05-02 09:15:12,A0003,HSIK3,2,22560.0,2013-05-02 09:15:12.000,22549.0,2013-05-02 09:27:56.000,11.0,11.0
2013-05-02 09:15:53,A0004,HSIK3,2,22554.0,2013-05-02 09:15:53.000,22529.0,2013-05-02 09:16:26.000,25.0,25.0
2013-05-02 09:15:55,A0005,HSIK3,1,22553.0,2013-05-02 09:15:55.000,22526.0,2013-05-02 09:19:00.000,-27.0,-27.0
2013-05-02 09:16:21,A0001,HSIK3,2,22524.0,2013-05-02 09:16:21.000,22420.0,2013-05-02 09:35:12.000,104.0,104.0
2013-05-02 09:17:08,A0006,HSIK3,1,22535.0,2013-05-02 09:17:08.000,22563.0,2013-05-02 09:23:30.000,28.0,28.0
2013-05-02 09:18:56,A0007,HSIK3,1,22528.0,2013-05-02 09:18:56.000,22548.0,2013-05-02 09:26:14.000,20.0,20.0
2013-05-02 09:19:49,A0008,HSIK3,2,22527.0,2013-05-02 09:19:49.000,22421.0,2013-05-02 09:35:15.000,106.0,106.0
2013-05-02 09:22:39,A0004,HSIK3,2,22513.0,2013-05-02 09:22:39.000,22555.0,2013-05-02 09:23:16.000,-42.0,-17.0
2013-05-02 09:22:47,A0009,HSIK3,2,22515.0,2013-05-02 09:22:47.000,22562.0,2013-05-02 09:23:23.000,-47.0,-47.0
2013-05-02 09:23:07,A0010,HSIK3,1,22540.0,2013-05-02 09:23:07.000,22555.0,2013-05-02 09:25:44.000,15.0,15.0
2013-05-02 09:24:09,A0009,HSIK3,2,22552.0,2013-05-02 09:24:09.000,22539.0,2013-05-02 09:24:40.000,13.0,-34.0
2013-05-02 09:24:45,A0011,HSIK3,2,22543.0,2013-05-02 09:24:45.000,22540.0,2013-05-02 09:29:48.000,3.0,3.0
2013-05-02 09:25:00,A0012,HSIK3,2,22549.0,2013-05-02 09:25:00.000,22445.0,2013-05-02 09:33:02.000,104.0,104.0
2013-05-02 09:26:24,A0007,HSIK3,1,22542.0,2013-05-02 09:26:24.000,22495.0,2013-05-02 09:32:36.000,-47.0,-27.0
2013-05-02 09:29:04,A0004,HSIK3,2,22538.0,2013-05-02 09:29:04.000,22528.0,2013-05-02 09:30:47.000,10.0,-7.0
2013-05-02 09:30:16,A0009,HSIK3,2,22514.0,2013-05-02 09:30:16.000,22443.0,2013-05-02 09:33:16.000,71.0,37.0
2013-05-02 09:30:30,A0006,HSIK3,1,22534.0,2013-05-02 09:30:30.000,22487.0,2013-05-02 09:32:39.000,-47.0,-19.0
2013-05-02 09:31:06,A0003,HSIK3,2,22510.0,2013-05-02 09:31:06.000,22452.0,2013-05-02 09:32:57.000,58.0,69.0
2013-05-02 09:31:25,A0004,HSIK3,2,22508.0,2013-05-02 09:31:25.000,22499.0,2013-05-02 09:32:00.000,9.0,2.0
2013-05-02 09:32:51,A0004,HSIK3,2,22451.0,2013-05-02 09:32:51.000,22434.0,2013-05-02 09:33:35.000,17.0,19.0
2013-05-02 09:33:04,A0007,HSIK3,1,22442.0,2013-05-02 09:33:04.000,22490.0,2013-05-02 09:41:04.000,48.0,21.0
2013-05-02 09:33:16,A0006,HSIK3,1,22442.0,2013-05-02 09:33:16.000,22470.0,2013-05-02 09:36:23.000,28.0,9.0
2013-05-02 09:35:23,A0013,HSIK3,1,22425.0,2013-05-02 09:35:23.000,22459.0,2013-05-02 09:35:57.000,34.0,34.0
2013-05-02 09:35:34,A0006,HSIK3,1,22432.0,2013-05-02 09:35:34.000,22460.0,2013-05-02 09:36:12.000,28.0,37.0
2013-05-02 09:36:08,A0001,HSIK3,2,22457.0,2013-05-02 09:36:08.000,22451.0,2013-05-02 09:48:12.000,6.0,110.0
2013-05-02 09:37:18,A0012,HSIK3,1,22472.0,2013-05-02 09:37:18.000,22481.0,2013-05-02 09:43:45.000,9.0,113.0
2013-05-02 09:37:19,A0010,HSIK3,1,22472.0,2013-05-02 09:37:19.000,22518.0,2013-05-02 10:15:28.000,46.0,61.0
2013-05-02 09:38:03,A0002,HSIK3,2,22476.0,2013-05-02 09:38:03.000,22461.0,2013-05-02 09:38:38.000,15.0,119.0
2013-05-02 09:39:46,A0001,HSIK3,2,22481.0,2013-05-02 09:39:46.000,22453.0,2013-05-02 09:46:17.000,28.0,138.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 14:51:03,A0035,HSIK3,1,22578.0,2013-05-02 14:51:03.000,22531.0,2013-05-02 15:15:23.000,-47.0,-122.0
2013-05-02 14:53:50,A0035,HSIK3,1,22591.0,2013-05-02 14:53:50.000,22544.0,2013-05-02 15:13:43.000,-47.0,-169.0
2013-05-02 14:54:20,A0036,HSIK3,2,22582.0,2013-05-02 14:54:20.000,22562.0,2013-05-02 14:59:25.000,20.0,40.0
2013-05-02 14:57:51,A0015,HSIK3,2,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:04:48,A0007,HSIK3,1,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:20,A0003,HSIK3,2,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:12:21,A0004,HSIK3,2,22546.0,2013-05-02 15:12:21.000,22542.0,2013-05-02 15:15:08.000,4.0,42.0
2013-05-02 15:12:25,A0009,HSIK3,2,22545.0,2013-05-02 15:12:25.000,22543.0,2013-05-02 15:13:55.000,2.0,11.0
2013-05-02 15:15:31,A0021,HSIK3,1,22535.0,2013-05-02 15:15:31.000,22547.0,2013-05-02 15:17:18.000,12.0,-16.0
2013-05-02 15:15:47,A0037,HSIK3,2,22534.0,2013-05-02 15:15:47.000,22581.0,2013-05-02 16:13:53.000,-47.0,-47.0
2013-05-02 15:16:05,A0011,HSIK3,2,22539.0,2013-05-02 15:16:05.000,22529.0,2013-05-02 15:24:17.000,10.0,16.0
2013-05-02 15:18:16,A0021,HSIK3,1,22540.0,2013-05-02 15:18:16.000,22546.0,2013-05-02 15:29:34.000,6.0,-10.0
2013-05-02 15:18:18,A0007,HSIK3,1,22540.0,2013-05-02 15:18:18.000,22555.0,2013-05-02 15:44:02.000,15.0,261.0
2013-05-02 15:18:26,A0035,HSIK3,1,22538.0,2013-05-02 15:18:26.000,22591.0,2013-05-02 16:14:56.000,53.0,-116.0
2013-05-02 15:18:56,A0026,HSIK3,1,22535.0,2013-05-02 15:18:56.000,22550.0,2013-05-02 15:48:01.000,15.0,-48.0
2013-05-02 15:18:59,A0035,HSIK3,1,22533.0,2013-05-02 15:18:59.000,22586.0,2013-05-02 16:14:49.000,53.0,-63.0
2013-05-02 15:19:31,A0035,HSIK3,1,22525.0,2013-05-02 15:19:31.000,22578.0,2013-05-02 16:13:01.000,53.0,-10.0
2013-05-02 15:21:18,A0036,HSIK3,1,22546.0,2013-05-02 15:21:18.000,22559.0,2013-05-02 15:43:58.000,13.0,53.0
2013-05-02 15:24:20,A0007,HSIK3,1,22532.0,2013-05-02 15:24:20.000,22551.0,2013-05-02 15:29:25.000,19.0,280.0
2013-05-02 15:29:45,A0007,HSIK3,1,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:46,A0010,HSIK3,1,22542.0,2013-05-02 15:30:46.000,22554.0,2013-05-02 15:47:27.000,12.0,202.0
2013-05-02 15:31:58,A0021,HSIK3,1,22550.0,2013-05-02 15:31:58.000,22557.0,2013-05-02 15:52:34.000,7.0,-3.0
2013-05-02 15:32:02,A0015,HSIK3,1,22546.0,2013-05-02 15:32:02.000,22555.0,2013-05-02 15:32:49.000,9.0,-7.0
2013-05-02 15:36:14,A0016,HSIK3,1,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:46:10,A0007,HSIK3,1,22545.0,2013-05-02 15:46:10.000,22555.0,2013-05-02 15:51:38.000,10.0,301.0
2013-05-02 15:46:49,A0015,HSIK3,2,22550.0,2013-05-02 15:46:49.000,22564.0,2013-05-02 15:55:21.000,-14.0,-21.0
2013-05-02 15:52:43,A0007,HSIK3,1,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:04,A0032,HSIK3,1,22565.0,2013-05-02 15:55:04.000,22581.0,2013-05-02 16:14:47.000,16.0,28.0
2013-05-02 15:58:42,A0007,HSIK3,1,22558.0,2013-05-02 15:58:42.000,22565.0,2013-05-02 16:02:40.000,7.0,319.0
2013-05-02 16:03:16,A0026,HSIK3,2,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [19]:
df3 = df2.resample('5min').max()
df3

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:00,A0008,HSIK3,2.0,22565.0,2013-05-02 09:19:49.000,22563.0,2013-05-02 09:35:15.000,106.0,106.0
2013-05-02 09:20:00,A0011,HSIK3,2.0,22552.0,2013-05-02 09:24:45.000,22562.0,2013-05-02 09:29:48.000,15.0,15.0
2013-05-02 09:25:00,A0012,HSIK3,2.0,22549.0,2013-05-02 09:29:04.000,22528.0,2013-05-02 09:33:02.000,104.0,104.0
2013-05-02 09:30:00,A0009,HSIK3,2.0,22534.0,2013-05-02 09:33:16.000,22499.0,2013-05-02 09:41:04.000,71.0,69.0
2013-05-02 09:35:00,A0013,HSIK3,2.0,22481.0,2013-05-02 09:39:46.000,22518.0,2013-05-02 10:15:28.000,46.0,138.0
2013-05-02 09:40:00,A0008,HSIK3,2.0,22493.0,2013-05-02 09:42:39.000,22479.0,2013-05-02 09:51:21.000,37.0,143.0
2013-05-02 09:45:00,A0014,HSIK3,2.0,22466.0,2013-05-02 09:48:43.000,22511.0,2013-05-02 10:11:45.000,57.0,170.0
2013-05-02 09:50:00,A0015,HSIK3,2.0,22452.0,2013-05-02 09:51:35.000,22505.0,2013-05-02 10:09:39.000,53.0,34.0
2013-05-02 09:55:00,A0006,HSIK3,1.0,22467.0,2013-05-02 09:56:33.000,22480.0,2013-05-02 10:07:47.000,13.0,61.0
2013-05-02 10:00:00,A0010,HSIK3,1.0,22456.0,2013-05-02 10:01:49.000,22484.0,2013-05-02 10:08:12.000,34.0,95.0
2013-05-02 10:05:00,A0017,HSIK3,1.0,22497.0,2013-05-02 10:09:38.000,22543.0,2013-05-02 10:10:14.000,53.0,53.0
2013-05-02 10:10:00,A0019,HSIK3,2.0,22540.0,2013-05-02 10:12:07.000,22530.0,2013-05-02 10:20:42.000,33.0,152.0
2013-05-02 10:15:00,A0021,HSIK3,2.0,22530.0,2013-05-02 10:19:35.000,22543.0,2013-05-02 10:56:42.000,34.0,153.0
2013-05-02 10:20:00,A0022,HSIK3,2.0,22518.0,2013-05-02 10:24:53.000,22600.0,2013-05-02 11:01:19.000,23.0,166.0
2013-05-02 10:25:00,A0022,HSIK3,2.0,22516.0,2013-05-02 10:29:29.000,22604.0,2013-05-02 11:01:19.000,23.0,66.0
2013-05-02 10:30:00,A0011,HSIK3,2.0,22512.0,2013-05-02 10:34:51.000,22508.0,2013-05-02 10:37:03.000,15.0,125.0
2013-05-02 10:35:00,A0014,HSIK3,2.0,22509.0,2013-05-02 10:39:51.000,22601.0,2013-05-02 11:01:19.000,20.0,137.0
2013-05-02 10:40:00,A0024,HSIK3,2.0,22518.0,2013-05-02 10:44:15.000,22539.0,2013-05-02 10:48:23.000,27.0,27.0
2013-05-02 10:45:00,A0019,HSIK3,2.0,22541.0,2013-05-02 10:49:30.000,22570.0,2013-05-02 10:58:11.000,31.0,132.0
2013-05-02 10:50:00,A0010,HSIK3,2.0,22543.0,2013-05-02 10:54:23.000,22552.0,2013-05-02 10:57:04.000,15.0,152.0
2013-05-02 10:55:00,A0021,HSIK3,2.0,22576.0,2013-05-02 10:59:37.000,22588.0,2013-05-02 11:04:26.000,24.0,161.0
2013-05-02 11:00:00,A0026,HSIK3,2.0,22592.0,2013-05-02 11:03:33.000,22583.0,2013-05-02 11:57:38.000,23.0,29.0
2013-05-02 11:05:00,A0028,HSIK3,2.0,22579.0,2013-05-02 11:09:20.000,22560.0,2013-05-02 14:31:39.000,31.0,172.0
2013-05-02 11:10:00,A0029,HSIK3,2.0,22570.0,2013-05-02 11:13:30.000,22560.0,2013-05-02 11:58:33.000,23.0,14.0
2013-05-02 11:15:00,A0030,HSIK3,2.0,22570.0,2013-05-02 11:18:55.000,22570.0,2013-05-02 11:29:44.000,10.0,-12.0
2013-05-02 11:20:00,A0031,HSIK3,2.0,22564.0,2013-05-02 11:24:42.000,22571.0,2013-05-02 11:49:56.000,11.0,125.0
2013-05-02 11:25:00,A0023,HSIK3,1.0,22565.0,2013-05-02 11:29:23.000,22575.0,2013-05-02 11:34:09.000,19.0,136.0
2013-05-02 11:30:00,A0025,HSIK3,2.0,22573.0,2013-05-02 11:34:56.000,22557.0,2013-05-02 11:53:11.000,14.0,28.0
2013-05-02 11:35:00,A0019,HSIK3,2.0,22574.0,2013-05-02 11:38:19.000,22567.0,2013-05-02 11:47:56.000,7.0,-10.0
2013-05-02 11:40:00,A0021,HSIK3,1.0,22566.0,2013-05-02 11:41:23.000,22557.0,2013-05-02 11:43:52.000,-9.0,-33.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 13:35:00,A0009,HSIK3,1.0,22522.0,2013-05-02 13:39:10.000,22544.0,2013-05-02 13:48:41.000,26.0,176.0
2013-05-02 13:40:00,A0026,HSIK3,2.0,22554.0,2013-05-02 13:43:10.000,22546.0,2013-05-02 13:57:27.000,8.0,18.0
2013-05-02 13:45:00,A0022,HSIK3,2.0,22544.0,2013-05-02 13:49:01.000,22558.0,2013-05-02 14:01:57.000,19.0,195.0
2013-05-02 13:50:00,A0033,HSIK3,2.0,22539.0,2013-05-02 13:52:08.000,22549.0,2013-05-02 14:01:16.000,26.0,221.0
2013-05-02 13:55:00,A0028,HSIK3,2.0,22539.0,2013-05-02 13:59:49.000,22579.0,2013-05-02 14:34:38.000,26.0,84.0
2013-05-02 14:00:00,A0028,HSIK3,2.0,22572.0,2013-05-02 14:04:58.000,22592.0,2013-05-02 15:24:23.000,16.0,228.0
2013-05-02 14:05:00,A0026,HSIK3,2.0,22573.0,2013-05-02 14:09:25.000,22577.0,2013-05-02 14:44:40.000,11.0,239.0
2013-05-02 14:10:00,A0020,HSIK3,2.0,22573.0,2013-05-02 14:11:50.000,22574.0,2013-05-02 14:49:58.000,10.0,248.0
2013-05-02 14:15:00,A0019,HSIK3,2.0,22567.0,2013-05-02 14:19:16.000,22574.0,2013-05-02 15:13:28.000,15.0,267.0
2013-05-02 14:20:00,A0034,HSIK3,2.0,22557.0,2013-05-02 14:24:19.000,22570.0,2013-05-02 14:37:06.000,13.0,109.0
2013-05-02 14:25:00,A0035,HSIK3,2.0,22563.0,2013-05-02 14:27:46.000,22569.0,2013-05-02 15:14:25.000,18.0,104.0
2013-05-02 14:30:00,A0035,HSIK3,2.0,22573.0,2013-05-02 14:34:11.000,22583.0,2013-05-02 14:48:32.000,13.0,117.0
2013-05-02 14:35:00,A0036,HSIK3,2.0,22582.0,2013-05-02 14:39:16.000,22571.0,2013-05-02 15:14:27.000,20.0,154.0
2013-05-02 14:40:00,A0006,HSIK3,2.0,22580.0,2013-05-02 14:44:23.000,22571.0,2013-05-02 14:47:52.000,19.0,173.0
2013-05-02 14:45:00,A0035,HSIK3,2.0,22572.0,2013-05-02 14:49:37.000,22584.0,2013-05-02 14:52:12.000,10.0,277.0
2013-05-02 14:50:00,A0036,HSIK3,2.0,22591.0,2013-05-02 14:54:20.000,22562.0,2013-05-02 15:15:23.000,20.0,40.0
2013-05-02 14:55:00,A0015,HSIK3,2.0,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:00:00,A0007,HSIK3,1.0,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:00,A0003,HSIK3,2.0,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:10:00,A0009,HSIK3,2.0,22546.0,2013-05-02 15:12:25.000,22543.0,2013-05-02 15:15:08.000,4.0,42.0
2013-05-02 15:15:00,A0037,HSIK3,2.0,22540.0,2013-05-02 15:19:31.000,22591.0,2013-05-02 16:14:56.000,53.0,261.0
2013-05-02 15:20:00,A0036,HSIK3,1.0,22546.0,2013-05-02 15:24:20.000,22559.0,2013-05-02 15:43:58.000,19.0,280.0
2013-05-02 15:25:00,A0007,HSIK3,1.0,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:00,A0021,HSIK3,1.0,22550.0,2013-05-02 15:32:02.000,22557.0,2013-05-02 15:52:34.000,12.0,202.0
2013-05-02 15:35:00,A0016,HSIK3,1.0,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-05-02 15:45:00,A0015,HSIK3,2.0,22550.0,2013-05-02 15:46:49.000,22564.0,2013-05-02 15:55:21.000,10.0,301.0
2013-05-02 15:50:00,A0007,HSIK3,1.0,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:00,A0032,HSIK3,1.0,22565.0,2013-05-02 15:58:42.000,22581.0,2013-05-02 16:14:47.000,16.0,319.0
2013-05-02 16:00:00,A0026,HSIK3,2.0,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [20]:
df4 = df2.resample('5min').min()
df4

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:00,A0001,HSIK3,1.0,22524.0,2013-05-02 09:15:05.000,22420.0,2013-05-02 09:16:26.000,-27.0,-27.0
2013-05-02 09:20:00,A0004,HSIK3,1.0,22513.0,2013-05-02 09:22:39.000,22539.0,2013-05-02 09:23:16.000,-47.0,-47.0
2013-05-02 09:25:00,A0004,HSIK3,1.0,22538.0,2013-05-02 09:25:00.000,22445.0,2013-05-02 09:30:47.000,-47.0,-27.0
2013-05-02 09:30:00,A0003,HSIK3,1.0,22442.0,2013-05-02 09:30:16.000,22434.0,2013-05-02 09:32:00.000,-47.0,-19.0
2013-05-02 09:35:00,A0001,HSIK3,1.0,22425.0,2013-05-02 09:35:23.000,22451.0,2013-05-02 09:35:57.000,6.0,34.0
2013-05-02 09:40:00,A0003,HSIK3,1.0,22477.0,2013-05-02 09:41:18.000,22439.0,2013-05-02 09:43:13.000,-47.0,-26.0
2013-05-02 09:45:00,A0004,HSIK3,1.0,22452.0,2013-05-02 09:45:21.000,22453.0,2013-05-02 09:46:12.000,4.0,-19.0
2013-05-02 09:50:00,A0004,HSIK3,1.0,22440.0,2013-05-02 09:50:27.000,22469.0,2013-05-02 09:52:43.000,-29.0,-19.0
2013-05-02 09:55:00,A0006,HSIK3,1.0,22467.0,2013-05-02 09:56:33.000,22480.0,2013-05-02 10:07:47.000,13.0,61.0
2013-05-02 10:00:00,A0004,HSIK3,1.0,22450.0,2013-05-02 10:00:04.000,22459.0,2013-05-02 10:00:54.000,3.0,4.0
2013-05-02 10:05:00,A0004,HSIK3,1.0,22468.0,2013-05-02 10:06:09.000,22481.0,2013-05-02 10:07:54.000,13.0,13.0
2013-05-02 10:10:00,A0007,HSIK3,1.0,22517.0,2013-05-02 10:10:02.000,22507.0,2013-05-02 10:10:33.000,7.0,7.0
2013-05-02 10:15:00,A0002,HSIK3,1.0,22519.0,2013-05-02 10:15:34.000,22490.0,2013-05-02 10:20:26.000,8.0,10.0
2013-05-02 10:20:00,A0002,HSIK3,1.0,22489.0,2013-05-02 10:20:08.000,22482.0,2013-05-02 10:21:29.000,-96.0,-59.0
2013-05-02 10:25:00,A0014,HSIK3,2.0,22508.0,2013-05-02 10:26:06.000,22493.0,2013-05-02 10:32:58.000,-96.0,-155.0
2013-05-02 10:30:00,A0007,HSIK3,1.0,22485.0,2013-05-02 10:31:05.000,22494.0,2013-05-02 10:32:23.000,-12.0,6.0
2013-05-02 10:35:00,A0006,HSIK3,1.0,22492.0,2013-05-02 10:35:19.000,22490.0,2013-05-02 10:38:18.000,-96.0,-347.0
2013-05-02 10:40:00,A0005,HSIK3,1.0,22494.0,2013-05-02 10:40:03.000,22503.0,2013-05-02 10:40:36.000,-29.0,-79.0
2013-05-02 10:45:00,A0003,HSIK3,1.0,22519.0,2013-05-02 10:45:04.000,22525.0,2013-05-02 10:48:43.000,-47.0,-63.0
2013-05-02 10:50:00,A0005,HSIK3,1.0,22532.0,2013-05-02 10:51:25.000,22530.0,2013-05-02 10:52:43.000,2.0,-61.0
2013-05-02 10:55:00,A0005,HSIK3,1.0,22542.0,2013-05-02 10:55:37.000,22572.0,2013-05-02 10:57:25.000,-32.0,-93.0
2013-05-02 11:00:00,A0013,HSIK3,1.0,22588.0,2013-05-02 11:00:15.000,22545.0,2013-05-02 11:05:02.000,-47.0,-47.0
2013-05-02 11:05:00,A0007,HSIK3,1.0,22570.0,2013-05-02 11:05:05.000,22532.0,2013-05-02 11:11:19.000,-47.0,-6.0
2013-05-02 11:10:00,A0014,HSIK3,1.0,22564.0,2013-05-02 11:10:51.000,22541.0,2013-05-02 11:18:55.000,-12.0,-338.0
2013-05-02 11:15:00,A0019,HSIK3,2.0,22558.0,2013-05-02 11:18:09.000,22560.0,2013-05-02 11:25:09.000,-12.0,-17.0
2013-05-02 11:20:00,A0007,HSIK3,1.0,22560.0,2013-05-02 11:22:08.000,22559.0,2013-05-02 11:30:05.000,5.0,5.0
2013-05-02 11:25:00,A0005,HSIK3,1.0,22550.0,2013-05-02 11:27:18.000,22562.0,2013-05-02 11:29:01.000,10.0,-77.0
2013-05-02 11:30:00,A0021,HSIK3,1.0,22567.0,2013-05-02 11:31:30.000,22553.0,2013-05-02 11:43:54.000,-16.0,-24.0
2013-05-02 11:35:00,A0015,HSIK3,1.0,22574.0,2013-05-02 11:36:33.000,22562.0,2013-05-02 11:40:36.000,-12.0,-31.0
2013-05-02 11:40:00,A0021,HSIK3,1.0,22566.0,2013-05-02 11:41:23.000,22557.0,2013-05-02 11:43:52.000,-9.0,-33.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 13:35:00,A0007,HSIK3,1.0,22518.0,2013-05-02 13:38:35.000,22531.0,2013-05-02 13:41:30.000,9.0,20.0
2013-05-02 13:40:00,A0020,HSIK3,1.0,22546.0,2013-05-02 13:42:11.000,22531.0,2013-05-02 13:44:49.000,-15.0,-68.0
2013-05-02 13:45:00,A0003,HSIK3,1.0,22538.0,2013-05-02 13:45:10.000,22523.0,2013-05-02 13:47:55.000,-16.0,-4.0
2013-05-02 13:50:00,A0003,HSIK3,1.0,22523.0,2013-05-02 13:50:34.000,22524.0,2013-05-02 13:51:34.000,-8.0,23.0
2013-05-02 13:55:00,A0006,HSIK3,1.0,22531.0,2013-05-02 13:55:31.000,22529.0,2013-05-02 13:59:53.000,-47.0,-19.0
2013-05-02 14:00:00,A0007,HSIK3,2.0,22545.0,2013-05-02 14:00:36.000,22529.0,2013-05-02 14:06:19.000,-39.0,29.0
2013-05-02 14:05:00,A0003,HSIK3,1.0,22565.0,2013-05-02 14:05:28.000,22557.0,2013-05-02 14:07:54.000,5.0,-63.0
2013-05-02 14:10:00,A0003,HSIK3,1.0,22565.0,2013-05-02 14:10:22.000,22558.0,2013-05-02 14:13:53.000,6.0,3.0
2013-05-02 14:15:00,A0007,HSIK3,1.0,22557.0,2013-05-02 14:16:16.000,22548.0,2013-05-02 14:22:19.000,4.0,-18.0
2013-05-02 14:20:00,A0006,HSIK3,1.0,22555.0,2013-05-02 14:21:00.000,22548.0,2013-05-02 14:31:20.000,-1.0,2.0
2013-05-02 14:25:00,A0006,HSIK3,1.0,22558.0,2013-05-02 14:25:38.000,22545.0,2013-05-02 14:29:02.000,-11.0,-297.0
2013-05-02 14:30:00,A0006,HSIK3,1.0,22550.0,2013-05-02 14:30:46.000,22545.0,2013-05-02 14:31:35.000,-33.0,-43.0
2013-05-02 14:35:00,A0001,HSIK3,1.0,22561.0,2013-05-02 14:36:07.000,22545.0,2013-05-02 14:46:34.000,-36.0,-59.0
2013-05-02 14:40:00,A0001,HSIK3,1.0,22573.0,2013-05-02 14:40:14.000,22561.0,2013-05-02 14:41:04.000,-5.0,66.0
2013-05-02 14:45:00,A0007,HSIK3,1.0,22561.0,2013-05-02 14:47:20.000,22571.0,2013-05-02 14:49:34.000,-16.0,-75.0
2013-05-02 14:50:00,A0035,HSIK3,1.0,22578.0,2013-05-02 14:51:03.000,22531.0,2013-05-02 14:59:25.000,-47.0,-169.0
2013-05-02 14:55:00,A0015,HSIK3,2.0,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:00:00,A0007,HSIK3,1.0,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:00,A0003,HSIK3,2.0,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:10:00,A0004,HSIK3,2.0,22545.0,2013-05-02 15:12:21.000,22542.0,2013-05-02 15:13:55.000,2.0,11.0
2013-05-02 15:15:00,A0007,HSIK3,1.0,22525.0,2013-05-02 15:15:31.000,22529.0,2013-05-02 15:17:18.000,-47.0,-116.0
2013-05-02 15:20:00,A0007,HSIK3,1.0,22532.0,2013-05-02 15:21:18.000,22551.0,2013-05-02 15:29:25.000,13.0,53.0
2013-05-02 15:25:00,A0007,HSIK3,1.0,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:00,A0010,HSIK3,1.0,22542.0,2013-05-02 15:30:46.000,22554.0,2013-05-02 15:32:49.000,7.0,-7.0
2013-05-02 15:35:00,A0016,HSIK3,1.0,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-05-02 15:45:00,A0007,HSIK3,1.0,22545.0,2013-05-02 15:46:10.000,22555.0,2013-05-02 15:51:38.000,-14.0,-21.0
2013-05-02 15:50:00,A0007,HSIK3,1.0,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:00,A0007,HSIK3,1.0,22558.0,2013-05-02 15:55:04.000,22565.0,2013-05-02 16:02:40.000,7.0,28.0
2013-05-02 16:00:00,A0026,HSIK3,2.0,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [25]:
df5 = df2.resample('5min').first()
df5

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:00,A0002,HSIK3,2.0,22565.0,2013-05-02 09:15:05.000,22461.0,2013-05-02 09:32:49.000,104.0,104.0
2013-05-02 09:20:00,A0004,HSIK3,2.0,22513.0,2013-05-02 09:22:39.000,22555.0,2013-05-02 09:23:16.000,-42.0,-17.0
2013-05-02 09:25:00,A0012,HSIK3,2.0,22549.0,2013-05-02 09:25:00.000,22445.0,2013-05-02 09:33:02.000,104.0,104.0
2013-05-02 09:30:00,A0009,HSIK3,2.0,22514.0,2013-05-02 09:30:16.000,22443.0,2013-05-02 09:33:16.000,71.0,37.0
2013-05-02 09:35:00,A0013,HSIK3,1.0,22425.0,2013-05-02 09:35:23.000,22459.0,2013-05-02 09:35:57.000,34.0,34.0
2013-05-02 09:40:00,A0007,HSIK3,1.0,22486.0,2013-05-02 09:41:18.000,22439.0,2013-05-02 09:51:21.000,-47.0,-26.0
2013-05-02 09:45:00,A0004,HSIK3,2.0,22465.0,2013-05-02 09:45:21.000,22459.0,2013-05-02 09:46:44.000,6.0,30.0
2013-05-02 09:50:00,A0015,HSIK3,2.0,22452.0,2013-05-02 09:50:27.000,22471.0,2013-05-02 09:52:43.000,-19.0,-19.0
2013-05-02 09:55:00,A0006,HSIK3,1.0,22467.0,2013-05-02 09:56:33.000,22480.0,2013-05-02 10:07:47.000,13.0,61.0
2013-05-02 10:00:00,A0004,HSIK3,1.0,22456.0,2013-05-02 10:00:04.000,22459.0,2013-05-02 10:00:54.000,3.0,4.0
2013-05-02 10:05:00,A0016,HSIK3,1.0,22468.0,2013-05-02 10:06:09.000,22481.0,2013-05-02 10:07:54.000,13.0,13.0
2013-05-02 10:10:00,A0007,HSIK3,1.0,22520.0,2013-05-02 10:10:02.000,22530.0,2013-05-02 10:10:33.000,10.0,44.0
2013-05-02 10:15:00,A0020,HSIK3,2.0,22522.0,2013-05-02 10:15:34.000,22512.0,2013-05-02 10:28:39.000,10.0,10.0
2013-05-02 10:20:00,A0002,HSIK3,2.0,22518.0,2013-05-02 10:20:08.000,22505.0,2013-05-02 10:21:29.000,13.0,166.0
2013-05-02 10:25:00,A0014,HSIK3,2.0,22508.0,2013-05-02 10:26:06.000,22604.0,2013-05-02 11:01:19.000,-96.0,-155.0
2013-05-02 10:30:00,A0007,HSIK3,1.0,22512.0,2013-05-02 10:31:05.000,22500.0,2013-05-02 10:32:23.000,-12.0,66.0
2013-05-02 10:35:00,A0014,HSIK3,2.0,22492.0,2013-05-02 10:35:19.000,22588.0,2013-05-02 11:00:00.000,-96.0,-251.0
2013-05-02 10:40:00,A0023,HSIK3,1.0,22494.0,2013-05-02 10:40:03.000,22521.0,2013-05-02 10:47:05.000,27.0,27.0
2013-05-02 10:45:00,A0018,HSIK3,2.0,22519.0,2013-05-02 10:45:04.000,22566.0,2013-05-02 10:57:15.000,-47.0,19.0
2013-05-02 10:50:00,A0005,HSIK3,2.0,22532.0,2013-05-02 10:51:25.000,22530.0,2013-05-02 10:52:43.000,2.0,-61.0
2013-05-02 10:55:00,A0005,HSIK3,2.0,22542.0,2013-05-02 10:55:37.000,22574.0,2013-05-02 10:59:42.000,-32.0,-93.0
2013-05-02 11:00:00,A0019,HSIK3,2.0,22588.0,2013-05-02 11:00:15.000,22583.0,2013-05-02 11:06:02.000,5.0,-27.0
2013-05-02 11:05:00,A0007,HSIK3,1.0,22579.0,2013-05-02 11:05:05.000,22532.0,2013-05-02 13:03:00.000,-47.0,114.0
2013-05-02 11:10:00,A0029,HSIK3,2.0,22566.0,2013-05-02 11:10:51.000,22552.0,2013-05-02 11:52:59.000,14.0,14.0
2013-05-02 11:15:00,A0019,HSIK3,2.0,22570.0,2013-05-02 11:18:09.000,22560.0,2013-05-02 11:25:09.000,10.0,-17.0
2013-05-02 11:20:00,A0031,HSIK3,2.0,22564.0,2013-05-02 11:22:08.000,22559.0,2013-05-02 11:49:56.000,5.0,5.0
2013-05-02 11:25:00,A0023,HSIK3,1.0,22556.0,2013-05-02 11:27:18.000,22569.0,2013-05-02 11:33:19.000,13.0,40.0
2013-05-02 11:30:00,A0025,HSIK3,2.0,22567.0,2013-05-02 11:31:30.000,22553.0,2013-05-02 11:53:11.000,14.0,28.0
2013-05-02 11:35:00,A0019,HSIK3,2.0,22574.0,2013-05-02 11:36:33.000,22567.0,2013-05-02 11:40:36.000,7.0,-10.0
2013-05-02 11:40:00,A0021,HSIK3,1.0,22566.0,2013-05-02 11:41:23.000,22557.0,2013-05-02 11:43:52.000,-9.0,-33.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 13:35:00,A0007,HSIK3,1.0,22518.0,2013-05-02 13:38:35.000,22544.0,2013-05-02 13:48:41.000,26.0,176.0
2013-05-02 13:40:00,A0026,HSIK3,1.0,22546.0,2013-05-02 13:42:11.000,22531.0,2013-05-02 13:57:27.000,-15.0,-68.0
2013-05-02 13:45:00,A0019,HSIK3,2.0,22544.0,2013-05-02 13:45:10.000,22538.0,2013-05-02 13:47:55.000,6.0,-4.0
2013-05-02 13:50:00,A0020,HSIK3,2.0,22539.0,2013-05-02 13:50:34.000,22525.0,2013-05-02 13:51:34.000,14.0,32.0
2013-05-02 13:55:00,A0006,HSIK3,2.0,22539.0,2013-05-02 13:55:31.000,22533.0,2013-05-02 13:59:53.000,6.0,84.0
2013-05-02 14:00:00,A0028,HSIK3,2.0,22545.0,2013-05-02 14:00:36.000,22529.0,2013-05-02 15:24:23.000,16.0,68.0
2013-05-02 14:05:00,A0026,HSIK3,1.0,22572.0,2013-05-02 14:05:28.000,22577.0,2013-05-02 14:44:40.000,5.0,-63.0
2013-05-02 14:10:00,A0003,HSIK3,2.0,22572.0,2013-05-02 14:10:22.000,22566.0,2013-05-02 14:25:15.000,6.0,71.0
2013-05-02 14:15:00,A0019,HSIK3,2.0,22567.0,2013-05-02 14:16:16.000,22560.0,2013-05-02 14:27:26.000,7.0,3.0
2013-05-02 14:20:00,A0006,HSIK3,2.0,22555.0,2013-05-02 14:21:00.000,22548.0,2013-05-02 14:31:39.000,7.0,109.0
2013-05-02 14:25:00,A0014,HSIK3,2.0,22563.0,2013-05-02 14:25:38.000,22545.0,2013-05-02 15:14:25.000,18.0,-297.0
2013-05-02 14:30:00,A0035,HSIK3,2.0,22560.0,2013-05-02 14:30:46.000,22572.0,2013-05-02 14:34:05.000,-12.0,-18.0
2013-05-02 14:35:00,A0033,HSIK3,1.0,22582.0,2013-05-02 14:36:07.000,22546.0,2013-05-02 15:12:23.000,-36.0,-13.0
2013-05-02 14:40:00,A0001,HSIK3,2.0,22580.0,2013-05-02 14:40:14.000,22561.0,2013-05-02 14:47:52.000,19.0,173.0
2013-05-02 14:45:00,A0016,HSIK3,2.0,22563.0,2013-05-02 14:47:20.000,22577.0,2013-05-02 14:49:46.000,-14.0,-12.0
2013-05-02 14:50:00,A0035,HSIK3,1.0,22578.0,2013-05-02 14:51:03.000,22531.0,2013-05-02 15:15:23.000,-47.0,-122.0
2013-05-02 14:55:00,A0015,HSIK3,2.0,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:00:00,A0007,HSIK3,1.0,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:00,A0003,HSIK3,2.0,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:10:00,A0004,HSIK3,2.0,22546.0,2013-05-02 15:12:21.000,22542.0,2013-05-02 15:15:08.000,4.0,42.0
2013-05-02 15:15:00,A0021,HSIK3,1.0,22535.0,2013-05-02 15:15:31.000,22547.0,2013-05-02 15:17:18.000,12.0,-16.0
2013-05-02 15:20:00,A0036,HSIK3,1.0,22546.0,2013-05-02 15:21:18.000,22559.0,2013-05-02 15:43:58.000,13.0,53.0
2013-05-02 15:25:00,A0007,HSIK3,1.0,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:00,A0010,HSIK3,1.0,22542.0,2013-05-02 15:30:46.000,22554.0,2013-05-02 15:47:27.000,12.0,202.0
2013-05-02 15:35:00,A0016,HSIK3,1.0,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-05-02 15:45:00,A0007,HSIK3,1.0,22545.0,2013-05-02 15:46:10.000,22555.0,2013-05-02 15:51:38.000,10.0,301.0
2013-05-02 15:50:00,A0007,HSIK3,1.0,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:00,A0032,HSIK3,1.0,22565.0,2013-05-02 15:55:04.000,22581.0,2013-05-02 16:14:47.000,16.0,28.0
2013-05-02 16:00:00,A0026,HSIK3,2.0,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [26]:
df2

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:05,A0002,HSIK3,2,22565.0,2013-05-02 09:15:05.000,22461.0,2013-05-02 09:32:49.000,104.0,104.0
2013-05-02 09:15:12,A0003,HSIK3,2,22560.0,2013-05-02 09:15:12.000,22549.0,2013-05-02 09:27:56.000,11.0,11.0
2013-05-02 09:15:53,A0004,HSIK3,2,22554.0,2013-05-02 09:15:53.000,22529.0,2013-05-02 09:16:26.000,25.0,25.0
2013-05-02 09:15:55,A0005,HSIK3,1,22553.0,2013-05-02 09:15:55.000,22526.0,2013-05-02 09:19:00.000,-27.0,-27.0
2013-05-02 09:16:21,A0001,HSIK3,2,22524.0,2013-05-02 09:16:21.000,22420.0,2013-05-02 09:35:12.000,104.0,104.0
2013-05-02 09:17:08,A0006,HSIK3,1,22535.0,2013-05-02 09:17:08.000,22563.0,2013-05-02 09:23:30.000,28.0,28.0
2013-05-02 09:18:56,A0007,HSIK3,1,22528.0,2013-05-02 09:18:56.000,22548.0,2013-05-02 09:26:14.000,20.0,20.0
2013-05-02 09:19:49,A0008,HSIK3,2,22527.0,2013-05-02 09:19:49.000,22421.0,2013-05-02 09:35:15.000,106.0,106.0
2013-05-02 09:22:39,A0004,HSIK3,2,22513.0,2013-05-02 09:22:39.000,22555.0,2013-05-02 09:23:16.000,-42.0,-17.0
2013-05-02 09:22:47,A0009,HSIK3,2,22515.0,2013-05-02 09:22:47.000,22562.0,2013-05-02 09:23:23.000,-47.0,-47.0
2013-05-02 09:23:07,A0010,HSIK3,1,22540.0,2013-05-02 09:23:07.000,22555.0,2013-05-02 09:25:44.000,15.0,15.0
2013-05-02 09:24:09,A0009,HSIK3,2,22552.0,2013-05-02 09:24:09.000,22539.0,2013-05-02 09:24:40.000,13.0,-34.0
2013-05-02 09:24:45,A0011,HSIK3,2,22543.0,2013-05-02 09:24:45.000,22540.0,2013-05-02 09:29:48.000,3.0,3.0
2013-05-02 09:25:00,A0012,HSIK3,2,22549.0,2013-05-02 09:25:00.000,22445.0,2013-05-02 09:33:02.000,104.0,104.0
2013-05-02 09:26:24,A0007,HSIK3,1,22542.0,2013-05-02 09:26:24.000,22495.0,2013-05-02 09:32:36.000,-47.0,-27.0
2013-05-02 09:29:04,A0004,HSIK3,2,22538.0,2013-05-02 09:29:04.000,22528.0,2013-05-02 09:30:47.000,10.0,-7.0
2013-05-02 09:30:16,A0009,HSIK3,2,22514.0,2013-05-02 09:30:16.000,22443.0,2013-05-02 09:33:16.000,71.0,37.0
2013-05-02 09:30:30,A0006,HSIK3,1,22534.0,2013-05-02 09:30:30.000,22487.0,2013-05-02 09:32:39.000,-47.0,-19.0
2013-05-02 09:31:06,A0003,HSIK3,2,22510.0,2013-05-02 09:31:06.000,22452.0,2013-05-02 09:32:57.000,58.0,69.0
2013-05-02 09:31:25,A0004,HSIK3,2,22508.0,2013-05-02 09:31:25.000,22499.0,2013-05-02 09:32:00.000,9.0,2.0
2013-05-02 09:32:51,A0004,HSIK3,2,22451.0,2013-05-02 09:32:51.000,22434.0,2013-05-02 09:33:35.000,17.0,19.0
2013-05-02 09:33:04,A0007,HSIK3,1,22442.0,2013-05-02 09:33:04.000,22490.0,2013-05-02 09:41:04.000,48.0,21.0
2013-05-02 09:33:16,A0006,HSIK3,1,22442.0,2013-05-02 09:33:16.000,22470.0,2013-05-02 09:36:23.000,28.0,9.0
2013-05-02 09:35:23,A0013,HSIK3,1,22425.0,2013-05-02 09:35:23.000,22459.0,2013-05-02 09:35:57.000,34.0,34.0
2013-05-02 09:35:34,A0006,HSIK3,1,22432.0,2013-05-02 09:35:34.000,22460.0,2013-05-02 09:36:12.000,28.0,37.0
2013-05-02 09:36:08,A0001,HSIK3,2,22457.0,2013-05-02 09:36:08.000,22451.0,2013-05-02 09:48:12.000,6.0,110.0
2013-05-02 09:37:18,A0012,HSIK3,1,22472.0,2013-05-02 09:37:18.000,22481.0,2013-05-02 09:43:45.000,9.0,113.0
2013-05-02 09:37:19,A0010,HSIK3,1,22472.0,2013-05-02 09:37:19.000,22518.0,2013-05-02 10:15:28.000,46.0,61.0
2013-05-02 09:38:03,A0002,HSIK3,2,22476.0,2013-05-02 09:38:03.000,22461.0,2013-05-02 09:38:38.000,15.0,119.0
2013-05-02 09:39:46,A0001,HSIK3,2,22481.0,2013-05-02 09:39:46.000,22453.0,2013-05-02 09:46:17.000,28.0,138.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 14:51:03,A0035,HSIK3,1,22578.0,2013-05-02 14:51:03.000,22531.0,2013-05-02 15:15:23.000,-47.0,-122.0
2013-05-02 14:53:50,A0035,HSIK3,1,22591.0,2013-05-02 14:53:50.000,22544.0,2013-05-02 15:13:43.000,-47.0,-169.0
2013-05-02 14:54:20,A0036,HSIK3,2,22582.0,2013-05-02 14:54:20.000,22562.0,2013-05-02 14:59:25.000,20.0,40.0
2013-05-02 14:57:51,A0015,HSIK3,2,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:04:48,A0007,HSIK3,1,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:20,A0003,HSIK3,2,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:12:21,A0004,HSIK3,2,22546.0,2013-05-02 15:12:21.000,22542.0,2013-05-02 15:15:08.000,4.0,42.0
2013-05-02 15:12:25,A0009,HSIK3,2,22545.0,2013-05-02 15:12:25.000,22543.0,2013-05-02 15:13:55.000,2.0,11.0
2013-05-02 15:15:31,A0021,HSIK3,1,22535.0,2013-05-02 15:15:31.000,22547.0,2013-05-02 15:17:18.000,12.0,-16.0
2013-05-02 15:15:47,A0037,HSIK3,2,22534.0,2013-05-02 15:15:47.000,22581.0,2013-05-02 16:13:53.000,-47.0,-47.0
2013-05-02 15:16:05,A0011,HSIK3,2,22539.0,2013-05-02 15:16:05.000,22529.0,2013-05-02 15:24:17.000,10.0,16.0
2013-05-02 15:18:16,A0021,HSIK3,1,22540.0,2013-05-02 15:18:16.000,22546.0,2013-05-02 15:29:34.000,6.0,-10.0
2013-05-02 15:18:18,A0007,HSIK3,1,22540.0,2013-05-02 15:18:18.000,22555.0,2013-05-02 15:44:02.000,15.0,261.0
2013-05-02 15:18:26,A0035,HSIK3,1,22538.0,2013-05-02 15:18:26.000,22591.0,2013-05-02 16:14:56.000,53.0,-116.0
2013-05-02 15:18:56,A0026,HSIK3,1,22535.0,2013-05-02 15:18:56.000,22550.0,2013-05-02 15:48:01.000,15.0,-48.0
2013-05-02 15:18:59,A0035,HSIK3,1,22533.0,2013-05-02 15:18:59.000,22586.0,2013-05-02 16:14:49.000,53.0,-63.0
2013-05-02 15:19:31,A0035,HSIK3,1,22525.0,2013-05-02 15:19:31.000,22578.0,2013-05-02 16:13:01.000,53.0,-10.0
2013-05-02 15:21:18,A0036,HSIK3,1,22546.0,2013-05-02 15:21:18.000,22559.0,2013-05-02 15:43:58.000,13.0,53.0
2013-05-02 15:24:20,A0007,HSIK3,1,22532.0,2013-05-02 15:24:20.000,22551.0,2013-05-02 15:29:25.000,19.0,280.0
2013-05-02 15:29:45,A0007,HSIK3,1,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:46,A0010,HSIK3,1,22542.0,2013-05-02 15:30:46.000,22554.0,2013-05-02 15:47:27.000,12.0,202.0
2013-05-02 15:31:58,A0021,HSIK3,1,22550.0,2013-05-02 15:31:58.000,22557.0,2013-05-02 15:52:34.000,7.0,-3.0
2013-05-02 15:32:02,A0015,HSIK3,1,22546.0,2013-05-02 15:32:02.000,22555.0,2013-05-02 15:32:49.000,9.0,-7.0
2013-05-02 15:36:14,A0016,HSIK3,1,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:46:10,A0007,HSIK3,1,22545.0,2013-05-02 15:46:10.000,22555.0,2013-05-02 15:51:38.000,10.0,301.0
2013-05-02 15:46:49,A0015,HSIK3,2,22550.0,2013-05-02 15:46:49.000,22564.0,2013-05-02 15:55:21.000,-14.0,-21.0
2013-05-02 15:52:43,A0007,HSIK3,1,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:04,A0032,HSIK3,1,22565.0,2013-05-02 15:55:04.000,22581.0,2013-05-02 16:14:47.000,16.0,28.0
2013-05-02 15:58:42,A0007,HSIK3,1,22558.0,2013-05-02 15:58:42.000,22565.0,2013-05-02 16:02:40.000,7.0,319.0
2013-05-02 16:03:16,A0026,HSIK3,2,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [27]:
df6 = df2.resample('5min').last()
df6

,account,product,buy_sell,take_price,take_time,close_price,close_time,profit,sum_profit
2013-05-02 09:15:00,A0008,HSIK3,2.0,22527.0,2013-05-02 09:19:49.000,22421.0,2013-05-02 09:35:15.000,106.0,106.0
2013-05-02 09:20:00,A0011,HSIK3,2.0,22543.0,2013-05-02 09:24:45.000,22540.0,2013-05-02 09:29:48.000,3.0,3.0
2013-05-02 09:25:00,A0004,HSIK3,2.0,22538.0,2013-05-02 09:29:04.000,22528.0,2013-05-02 09:30:47.000,10.0,-7.0
2013-05-02 09:30:00,A0006,HSIK3,1.0,22442.0,2013-05-02 09:33:16.000,22470.0,2013-05-02 09:36:23.000,28.0,9.0
2013-05-02 09:35:00,A0001,HSIK3,2.0,22481.0,2013-05-02 09:39:46.000,22453.0,2013-05-02 09:46:17.000,28.0,138.0
2013-05-02 09:40:00,A0004,HSIK3,2.0,22477.0,2013-05-02 09:42:39.000,22472.0,2013-05-02 09:43:13.000,5.0,24.0
2013-05-02 09:45:00,A0012,HSIK3,1.0,22454.0,2013-05-02 09:48:43.000,22511.0,2013-05-02 10:11:45.000,57.0,170.0
2013-05-02 09:50:00,A0007,HSIK3,1.0,22452.0,2013-05-02 09:51:35.000,22505.0,2013-05-02 10:09:39.000,53.0,34.0
2013-05-02 09:55:00,A0006,HSIK3,1.0,22467.0,2013-05-02 09:56:33.000,22480.0,2013-05-02 10:07:47.000,13.0,61.0
2013-05-02 10:00:00,A0010,HSIK3,1.0,22450.0,2013-05-02 10:01:49.000,22484.0,2013-05-02 10:08:12.000,34.0,95.0
2013-05-02 10:05:00,A0004,HSIK3,1.0,22497.0,2013-05-02 10:09:38.000,22531.0,2013-05-02 10:10:12.000,34.0,38.0
2013-05-02 10:10:00,A0019,HSIK3,2.0,22523.0,2013-05-02 10:12:07.000,22516.0,2013-05-02 10:13:03.000,7.0,7.0
2013-05-02 10:15:00,A0019,HSIK3,2.0,22520.0,2013-05-02 10:19:35.000,22512.0,2013-05-02 10:20:26.000,8.0,15.0
2013-05-02 10:20:00,A0021,HSIK3,1.0,22511.0,2013-05-02 10:24:53.000,22482.0,2013-05-02 10:34:49.000,-29.0,-27.0
2013-05-02 10:25:00,A0022,HSIK3,2.0,22516.0,2013-05-02 10:29:29.000,22493.0,2013-05-02 10:32:58.000,23.0,14.0
2013-05-02 10:30:00,A0008,HSIK3,2.0,22485.0,2013-05-02 10:34:51.000,22494.0,2013-05-02 10:35:31.000,-9.0,125.0
2013-05-02 10:35:00,A0006,HSIK3,2.0,22496.0,2013-05-02 10:39:51.000,22523.0,2013-05-02 10:46:06.000,-27.0,34.0
2013-05-02 10:40:00,A0005,HSIK3,2.0,22516.0,2013-05-02 10:44:15.000,22539.0,2013-05-02 10:48:15.000,-23.0,-79.0
2013-05-02 10:45:00,A0003,HSIK3,2.0,22529.0,2013-05-02 10:49:30.000,22542.0,2013-05-02 10:51:44.000,-13.0,63.0
2013-05-02 10:50:00,A0010,HSIK3,1.0,22537.0,2013-05-02 10:54:23.000,22552.0,2013-05-02 10:57:04.000,15.0,152.0
2013-05-02 10:55:00,A0013,HSIK3,2.0,22576.0,2013-05-02 10:59:37.000,22586.0,2013-05-02 11:00:31.000,-10.0,-2.0
2013-05-02 11:00:00,A0026,HSIK3,1.0,22592.0,2013-05-02 11:03:33.000,22545.0,2013-05-02 11:57:38.000,-47.0,-47.0
2013-05-02 11:05:00,A0021,HSIK3,1.0,22575.0,2013-05-02 11:09:20.000,22560.0,2013-05-02 11:11:19.000,-15.0,-6.0
2013-05-02 11:10:00,A0014,HSIK3,2.0,22564.0,2013-05-02 11:13:30.000,22541.0,2013-05-02 11:58:33.000,23.0,-315.0
2013-05-02 11:15:00,A0030,HSIK3,2.0,22558.0,2013-05-02 11:18:55.000,22570.0,2013-05-02 11:29:44.000,-12.0,-12.0
2013-05-02 11:20:00,A0007,HSIK3,1.0,22560.0,2013-05-02 11:24:42.000,22571.0,2013-05-02 11:30:05.000,11.0,125.0
2013-05-02 11:25:00,A0021,HSIK3,1.0,22565.0,2013-05-02 11:29:23.000,22575.0,2013-05-02 11:34:09.000,10.0,-8.0
2013-05-02 11:30:00,A0021,HSIK3,1.0,22573.0,2013-05-02 11:34:56.000,22557.0,2013-05-02 11:43:54.000,-16.0,-24.0
2013-05-02 11:35:00,A0015,HSIK3,1.0,22574.0,2013-05-02 11:38:19.000,22562.0,2013-05-02 11:47:56.000,-12.0,-31.0
2013-05-02 11:40:00,A0021,HSIK3,1.0,22566.0,2013-05-02 11:41:23.000,22557.0,2013-05-02 11:43:52.000,-9.0,-33.0
...,...,...,...,...,...,...,...,...,...
2013-05-02 13:35:00,A0009,HSIK3,1.0,22522.0,2013-05-02 13:39:10.000,22531.0,2013-05-02 13:41:30.000,9.0,20.0
2013-05-02 13:40:00,A0020,HSIK3,2.0,22554.0,2013-05-02 13:43:10.000,22546.0,2013-05-02 13:44:49.000,8.0,18.0
2013-05-02 13:45:00,A0007,HSIK3,1.0,22539.0,2013-05-02 13:49:01.000,22558.0,2013-05-02 14:01:57.000,19.0,195.0
2013-05-02 13:50:00,A0007,HSIK3,1.0,22523.0,2013-05-02 13:52:08.000,22549.0,2013-05-02 14:01:16.000,26.0,221.0
2013-05-02 13:55:00,A0025,HSIK3,2.0,22532.0,2013-05-02 13:59:49.000,22579.0,2013-05-02 14:34:38.000,-47.0,-19.0
2013-05-02 14:00:00,A0007,HSIK3,2.0,22572.0,2013-05-02 14:04:58.000,22565.0,2013-05-02 14:06:19.000,7.0,228.0
2013-05-02 14:05:00,A0003,HSIK3,2.0,22565.0,2013-05-02 14:09:25.000,22557.0,2013-05-02 14:21:44.000,8.0,65.0
2013-05-02 14:10:00,A0007,HSIK3,1.0,22565.0,2013-05-02 14:11:50.000,22574.0,2013-05-02 14:49:58.000,9.0,248.0
2013-05-02 14:15:00,A0015,HSIK3,2.0,22562.0,2013-05-02 14:19:16.000,22555.0,2013-05-02 14:22:19.000,7.0,-18.0
2013-05-02 14:20:00,A0034,HSIK3,1.0,22557.0,2013-05-02 14:24:19.000,22570.0,2013-05-02 14:37:06.000,13.0,13.0
2013-05-02 14:25:00,A0035,HSIK3,1.0,22563.0,2013-05-02 14:27:46.000,22557.0,2013-05-02 14:31:06.000,-6.0,-6.0
2013-05-02 14:30:00,A0035,HSIK3,1.0,22573.0,2013-05-02 14:34:11.000,22561.0,2013-05-02 14:48:32.000,-12.0,-43.0
2013-05-02 14:35:00,A0009,HSIK3,1.0,22582.0,2013-05-02 14:39:16.000,22571.0,2013-05-02 14:46:42.000,-11.0,9.0
2013-05-02 14:40:00,A0003,HSIK3,1.0,22574.0,2013-05-02 14:44:23.000,22569.0,2013-05-02 14:46:23.000,-5.0,66.0
2013-05-02 14:45:00,A0015,HSIK3,2.0,22572.0,2013-05-02 14:49:37.000,22584.0,2013-05-02 14:52:12.000,-12.0,-30.0
2013-05-02 14:50:00,A0036,HSIK3,2.0,22582.0,2013-05-02 14:54:20.000,22562.0,2013-05-02 14:59:25.000,20.0,40.0
2013-05-02 14:55:00,A0015,HSIK3,2.0,22575.0,2013-05-02 14:57:51.000,22561.0,2013-05-02 15:04:51.000,14.0,-16.0
2013-05-02 15:00:00,A0007,HSIK3,1.0,22565.0,2013-05-02 15:04:48.000,22534.0,2013-05-02 15:20:00.000,-31.0,246.0
2013-05-02 15:05:00,A0003,HSIK3,2.0,22566.0,2013-05-02 15:05:20.000,22534.0,2013-05-02 15:15:35.000,32.0,98.0
2013-05-02 15:10:00,A0009,HSIK3,2.0,22545.0,2013-05-02 15:12:25.000,22543.0,2013-05-02 15:13:55.000,2.0,11.0
2013-05-02 15:15:00,A0035,HSIK3,1.0,22525.0,2013-05-02 15:19:31.000,22578.0,2013-05-02 16:13:01.000,53.0,-10.0
2013-05-02 15:20:00,A0007,HSIK3,1.0,22532.0,2013-05-02 15:24:20.000,22551.0,2013-05-02 15:29:25.000,19.0,280.0
2013-05-02 15:25:00,A0007,HSIK3,1.0,22541.0,2013-05-02 15:29:45.000,22552.0,2013-05-02 15:47:03.000,11.0,291.0
2013-05-02 15:30:00,A0015,HSIK3,1.0,22546.0,2013-05-02 15:32:02.000,22555.0,2013-05-02 15:32:49.000,9.0,-7.0
2013-05-02 15:35:00,A0016,HSIK3,1.0,22546.0,2013-05-02 15:36:14.000,22552.0,2013-05-02 15:45:27.000,6.0,-6.0
2013-05-02 15:40:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-05-02 15:45:00,A0015,HSIK3,2.0,22550.0,2013-05-02 15:46:49.000,22564.0,2013-05-02 15:55:21.000,-14.0,-21.0
2013-05-02 15:50:00,A0007,HSIK3,1.0,22552.0,2013-05-02 15:52:43.000,22563.0,2013-05-02 16:08:00.000,11.0,312.0
2013-05-02 15:55:00,A0007,HSIK3,1.0,22558.0,2013-05-02 15:58:42.000,22565.0,2013-05-02 16:02:40.000,7.0,319.0
2013-05-02 16:00:00,A0026,HSIK3,2.0,22565.0,2013-05-02 16:03:16.000,22559.0,2013-05-02 16:08:58.000,6.0,-42.0

In [28]:
df7 = df2.resample('5min').sum()
df7

                     buy_sell  take_price  close_price  profit  sum_profit
2013-05-02 09:15:00      13.0    180346.0     180017.0   371.0       371.0
2013-05-02 09:20:00       9.0    112663.0     112751.0   -58.0       -80.0
2013-05-02 09:25:00       5.0     67629.0      67468.0    67.0        70.0
2013-05-02 09:30:00      11.0    157401.0     157275.0   184.0       138.0
2013-05-02 09:35:00      10.0    157215.0     157283.0   166.0       612.0
2013-05-02 09:40:00       7.0     89942.0      89846.0     2.0       217.0
2013-05-02 09:45:00       8.0    112301.0     112344.0    85.0       233.0
2013-05-02 09:50:00       5.0     67344.0      67445.0     5.0        16.0
2013-05-02 09:55:00       1.0     22467.0      22480.0    13.0        61.0
2013-05-02 10:00:00       2.0     44906.0      44943.0    37.0        99.0
2013-05-02 10:05:00       3.0     67455.0      67555.0   100.0       104.0
2013-05-02 10:10:00      10.0    135161.0     135105.0    96.0       321.0
2013-05-02 10:15:00      10.0    135134.0     135096.0   108.0       315.0
2013-05-02 10:20:00      13.0    157533.0     157600.0  -125.0       325.0
2013-05-02 10:25:00       6.0     67537.0      67592.0   -55.0       -75.0
2013-05-02 10:30:00       6.0     89988.0      89997.0    -3.0       278.0
2013-05-02 10:35:00       9.0    112502.0     112722.0  -180.0      -326.0
2013-05-02 10:40:00       8.0    135032.0     135141.0     5.0      -122.0
2013-05-02 10:45:00      10.0    135171.0     135314.0   -39.0       174.0
2013-05-02 10:50:00       4.0     67612.0      67630.0    22.0       228.0
2013-05-02 10:55:00       8.0    112801.0     112908.0   -29.0        83.0
2013-05-02 11:00:00       9.0    112953.0     112854.0     5.0       -10.0
2013-05-02 11:05:00      10.0    135454.0     135299.0    31.0       384.0
2013-05-02 11:10:00       7.0     90269.0      90211.0    34.0      -657.0
2013-05-02 11:15:00       4.0     45128.0      45130.0    -2.0       -29.0
2013-05-02 11:20:00       3.0     45124.0      45130.0    16.0       130.0
2013-05-02 11:25:00       6.0    135328.0     135415.0    87.0       226.0
2013-05-02 11:30:00       3.0     45140.0      45110.0    -2.0         4.0
2013-05-02 11:35:00       3.0     45148.0      45129.0    -5.0       -41.0
2013-05-02 11:40:00       1.0     22566.0      22557.0    -9.0       -33.0
...                       ...         ...          ...     ...         ...
2013-05-02 13:35:00       2.0     45040.0      45075.0    35.0       196.0
2013-05-02 13:40:00       3.0     45100.0      45077.0    -7.0       -50.0
2013-05-02 13:45:00       7.0    112702.0     112681.0    27.0       348.0
2013-05-02 13:50:00       5.0     90131.0      90141.0    38.0       333.0
2013-05-02 13:55:00       9.0    112679.0     112774.0   -43.0       152.0
2013-05-02 14:00:00       6.0     67670.0      67686.0   -16.0       325.0
2013-05-02 14:05:00       8.0    112847.0     112831.0    38.0       308.0
2013-05-02 14:10:00       7.0     90276.0      90261.0    33.0       424.0
2013-05-02 14:15:00       8.0    112803.0     112798.0    43.0       705.0
2013-05-02 14:20:00       5.0     67669.0      67676.0    19.0       124.0
2013-05-02 14:25:00       6.0     90247.0      90229.0    -4.0      -197.0
2013-05-02 14:30:00       9.0    112800.0     112833.0   -57.0        -5.0
2013-05-02 14:35:00       8.0    135461.0     135352.0   -37.0       103.0
2013-05-02 14:40:00       7.0     90307.0      90270.0    27.0       495.0
2013-05-02 14:45:00       7.0     90257.0      90309.0   -32.0       160.0
2013-05-02 14:50:00       4.0     67751.0      67637.0   -74.0      -251.0
2013-05-02 14:55:00       2.0     22575.0      22561.0    14.0       -16.0
2013-05-02 15:00:00       1.0     22565.0      22534.0   -31.0       246.0
2013-05-02 15:05:00       2.0     22566.0      22534.0    32.0        98.0
2013-05-02 15:10:00       4.0     45091.0      45085.0     6.0        53.0
2013-05-02 15:15:00      11.0    202819.0     203063.0   170.0       -33.0
2013-05-02 15:20:00       2.0     45078.0      45110.0    32.0       333.0
2013-05-02 15:25:00       1.0     22541.0      22552.0    11.0       291.0
2013-05-02 15:30:00       3.0     67638.0      67666.0    28.0       192.0
2013-05-02 15:35:00       1.0     22546.0      22552.0     6.0        -6.0
2013-05-02 15:40:00       NaN         NaN          NaN     NaN         NaN
2013-05-02 15:45:00       3.0     45095.0      45119.0    -4.0       280.0
2013-05-02 15:50:00       1.0     22552.0      22563.0    11.0       312.0
2013-05-02 15:55:00       2.0     45123.0      45146.0    23.0       347.0
2013-05-02 16:00:00       2.0     22565.0      22559.0     6.0       -42.0

[82 rows x 5 columns]

In [31]:
pro_ret = (df7.profit - df7.profit.shift(1))/df.profit.shift(1)
pro_ret

2013-05-02 09:15:00          NaN
2013-05-02 09:15:05          NaN
2013-05-02 09:15:12          NaN
2013-05-02 09:15:53          NaN
2013-05-02 09:15:55          NaN
2013-05-02 09:16:21          NaN
2013-05-02 09:17:08          NaN
2013-05-02 09:18:56          NaN
2013-05-02 09:19:49          NaN
2013-05-02 09:20:00          NaN
2013-05-02 09:22:39          NaN
2013-05-02 09:22:47          NaN
2013-05-02 09:23:07          NaN
2013-05-02 09:24:09          NaN
2013-05-02 09:24:45          NaN
2013-05-02 09:25:00    41.666667
2013-05-02 09:26:24          NaN
2013-05-02 09:29:04          NaN
2013-05-02 09:30:00          NaN
2013-05-02 09:30:16          NaN
2013-05-02 09:30:30          NaN
2013-05-02 09:31:06          NaN
2013-05-02 09:31:25          NaN
2013-05-02 09:32:51          NaN
2013-05-02 09:33:04          NaN
2013-05-02 09:33:16          NaN
2013-05-02 09:35:00          NaN
2013-05-02 09:35:23          NaN
2013-05-02 09:35:34          NaN
2013-05-02 09:36:08          NaN
                         ...
2015-12-30 15:37:27          NaN
2015-12-30 15:37:54          NaN
2015-12-30 15:39:08          NaN
2015-12-30 15:39:14          NaN
2015-12-30 15:39:24          NaN
2015-12-30 15:40:09          NaN
2015-12-30 15:40:42          NaN
2015-12-30 15:40:58          NaN
2015-12-30 15:44:52          NaN
2015-12-30 15:45:11          NaN
2015-12-30 15:45:33          NaN
2015-12-30 15:45:47          NaN
2015-12-30 15:46:34          NaN
2015-12-30 15:48:11          NaN
2015-12-30 15:48:19          NaN
2015-12-30 15:50:32          NaN
2015-12-30 15:51:13          NaN
2015-12-30 15:52:10          NaN
2015-12-30 15:52:42          NaN
2015-12-30 15:52:57          NaN
2015-12-30 15:53:05          NaN
2015-12-30 15:56:14          NaN
2015-12-30 15:56:51          NaN
2015-12-30 15:57:40          NaN
2015-12-30 15:58:29          NaN
2015-12-30 15:58:41          NaN
2015-12-30 15:59:19          NaN
2015-12-30 15:59:20          NaN
2015-12-30 15:59:28          NaN
2015-12-30 16:08:16          NaN
Name: profit, Length: 402841, dtype: float64