In [1]:
import pandas as pd

In [2]:
df = pd.read_hdf('C:/Users/Administrator/Desktop/Work/data/CTA_trade_detail_all/trade_detail_001810115002.h5')
df

,instrument,order_no,trade_time,direction,order_price,lots,turnover,open_close,fee,realized_pl,real_trade_date
0,C1709,10397523,13:31:28,1,1670.0,5,83500.0,0,3.05,0.0,2017-07-17
1,C1709,10424539,13:42:18,1,1669.0,3,50070.0,0,1.83,0.0,2017-07-17
2,MA709,01736313,13:47:54,0,2502.0,1,25020.0,0,2.04,0.0,2017-07-17
3,MA709,01736315,13:47:54,0,2502.0,2,50040.0,0,4.08,0.0,2017-07-17
4,MA709,01743943,13:49:44,0,2501.0,2,50020.0,0,4.08,0.0,2017-07-17
5,C1709,10438422,13:50:38,0,1673.0,8,133840.0,1,4.88,-270.0,2017-07-17
6,L1709,30479260,13:52:29,0,9200.0,2,92000.0,0,4.08,0.0,2017-07-17
7,RU1709,01716175,13:53:04,0,13560.0,1,135600.0,0,6.22,0.0,2017-07-17
8,MA709,01772932,13:57:01,0,2501.0,3,75030.0,0,6.12,0.0,2017-07-17
9,MA709,01791156,14:00:51,1,2496.0,1,24960.0,1,6.12,-60.0,2017-07-17
10,RU1709,01769795,14:05:35,1,13515.0,1,135150.0,1,24.81,-450.0,2017-07-17
11,MA709,01822370,14:06:07,1,2495.0,2,49900.0,1,12.24,-140.0,2017-07-17
12,MA709,01822756,14:06:13,1,2495.0,2,49900.0,1,12.24,-120.0,2017-07-17
13,L1709,30498397,14:07:10,1,9190.0,1,45950.0,1,2.04,-50.0,2017-07-17
14,MA709,01838051,14:08:52,0,2496.0,1,24960.0,0,2.04,0.0,2017-07-17
15,MA709,01838053,14:08:52,0,2496.0,3,74880.0,0,6.12,0.0,2017-07-17
16,PP1709,30503055,14:11:09,0,8163.0,1,40815.0,0,5.00,0.0,2017-07-17
17,PP1709,30503589,14:11:41,0,8164.0,1,40820.0,0,5.00,0.0,2017-07-17
18,MA709,01870076,14:14:14,0,2496.0,3,74880.0,0,6.12,0.0,2017-07-17
19,L1709,30507395,14:14:50,0,9215.0,1,46075.0,0,2.04,0.0,2017-07-17
20,MA709,01895570,14:18:33,1,2491.0,3,74730.0,1,18.36,-300.0,2017-07-17
21,MA709,01895571,14:18:33,1,2491.0,1,24910.0,1,6.12,-50.0,2017-07-17
22,MA709,01895572,14:18:33,1,2491.0,3,74730.0,1,18.36,-150.0,2017-07-17
23,MA709,01895573,14:18:33,1,2491.0,1,24910.0,1,6.12,-50.0,2017-07-17
24,L1709,30516778,14:19:51,1,9195.0,2,91950.0,1,4.08,-125.0,2017-07-17
25,MA709,01919216,14:21:37,0,2492.0,2,49840.0,0,4.08,0.0,2017-07-17
26,MA709,01919218,14:21:37,0,2492.0,1,24920.0,0,2.04,0.0,2017-07-17
27,MA709,01936405,14:23:20,0,2488.0,1,24880.0,0,2.04,0.0,2017-07-17
28,PP1709,30523818,14:24:09,0,8161.0,1,40805.0,0,4.99,0.0,2017-07-17
29,MA709,01953813,14:25:32,0,2488.0,1,24880.0,0,2.04,0.0,2017-07-17
...,...,...,...,...,...,...,...,...,...,...,...
712,CS1801,10236507,09:46:39,1,1945.0,5,97250.0,0,7.65,0.0,2017-10-16
713,CS1801,10238773,09:49:44,1,1946.0,1,19460.0,0,1.53,0.0,2017-10-16
714,CS1801,10238774,09:49:44,1,1946.0,1,19460.0,0,1.53,0.0,2017-10-16
715,CS1801,10238775,09:49:44,1,1946.0,3,58380.0,0,4.59,0.0,2017-10-16
716,CF801,01104921,09:54:33,1,15180.0,1,75900.0,0,4.39,0.0,2017-10-16
717,M1801,10249046,09:57:49,0,2847.0,1,28470.0,0,1.53,0.0,2017-10-16
718,RM801,01123260,09:57:59,0,2269.0,1,22690.0,0,1.53,0.0,2017-10-16
719,RB1801,01359307,10:03:06,0,3785.0,1,37850.0,1,3.86,-2280.0,2017-10-16
720,JD1801,10276305,10:36:38,0,4274.0,1,42740.0,0,6.54,0.0,2017-10-16
721,JD1801,10276646,10:36:48,0,4270.0,1,42700.0,0,6.53,0.0,2017-10-16
722,JD1801,10277269,10:37:00,0,4268.0,1,42680.0,0,6.53,0.0,2017-10-16
723,JD1801,10278248,10:37:20,0,4267.0,1,42670.0,0,6.53,0.0,2017-10-16
724,JD1801,10281132,10:38:55,0,4263.0,1,42630.0,0,6.52,0.0,2017-10-16
725,M1801,10284644,10:41:23,0,2849.0,2,56980.0,0,3.06,0.0,2017-10-16
726,M1801,10284823,10:41:36,0,2849.0,1,28490.0,0,1.53,0.0,2017-10-16
727,RB1801,01482022,10:50:52,1,3788.0,1,37880.0,1,3.86,2190.0,2017-10-16
728,JD1801,10303185,11:02:05,1,4267.0,1,42670.0,1,6.53,-70.0,2017-10-16
729,RM801,01264364,11:04:05,0,2272.0,1,22720.0,0,1.53,0.0,2017-10-16
730,RB1801,01544078,11:04:15,1,3788.0,1,37880.0,1,3.86,2410.0,2017-10-16
731,RM801,01269585,11:06:30,0,2272.0,1,22720.0,0,1.53,0.0,2017-10-16
732,RM801,01276785,11:09:28,0,2273.0,1,22730.0,0,1.53,0.0,2017-10-16
733,ZN1712,01587290,11:10:41,0,26145.0,1,130725.0,0,3.06,0.0,2017-10-16
734,ZN1712,01621064,11:16:18,0,26140.0,1,130700.0,0,3.06,0.0,2017-10-16
735,ZN1712,01651463,11:20:29,1,26005.0,1,130025.0,1,0.00,-700.0,2017-10-16
736,ZN1712,01654172,11:21:01,1,25970.0,1,129850.0,1,0.00,-850.0,2017-10-16
737,JD1801,10388902,14:49:21,0,4277.0,1,42770.0,0,6.54,0.0,2017-10-16
738,CS1801,10393544,14:52:30,0,1946.0,15,291900.0,1,22.95,2420.0,2017-10-16
739,JD1801,10400161,14:57:05,1,4265.0,1,42650.0,1,6.53,-50.0,2017-10-16
740,CF801,01669138,14:57:57,0,15215.0,1,76075.0,1,4.39,1150.0,2017-10-16
741,CF801,01672732,14:58:19,0,15225.0,1,76125.0,1,4.39,-475.0,2017-10-16

In [4]:
df1 = pd.read_hdf('C:/Users/Administrator/Desktop/Work/data/CTA_trade_detail_all/trade_detail_0158120301760.h5')
df1

,instrument,order_no,trade_time,direction,order_price,lots,turnover,open_close,fee,realized_pl,real_trade_date
0,MA709,00801137,09:02:09,0,2484.0,3,74520.0,0,6.18,0.0,2017-07-26
1,MA709,00825297,09:04:23,0,2484.0,2,49680.0,0,4.12,0.0,2017-07-26
2,Y1801,10235544,09:11:30,0,6288.0,1,62880.0,0,2.58,0.0,2017-07-26
3,MA709,00962920,09:16:36,0,2481.0,3,74430.0,0,6.18,0.0,2017-07-26
4,MA709,00974229,09:17:43,1,2477.0,1,24770.0,1,6.18,-70.0,2017-07-26
5,MA709,00974231,09:17:43,1,2477.0,1,24770.0,1,6.18,-70.0,2017-07-26
6,MA709,00974636,09:17:45,1,2476.0,1,24760.0,1,6.18,-80.0,2017-07-26
7,MA709,00974637,09:17:45,1,2476.0,2,49520.0,1,12.36,-160.0,2017-07-26
8,MA709,00974638,09:17:45,1,2476.0,3,74280.0,1,18.54,-150.0,2017-07-26
9,MA709,01013830,09:21:19,1,2470.0,3,74100.0,0,6.18,0.0,2017-07-26
10,BU1709,01113000,09:22:55,1,2636.0,4,105440.0,0,10.87,0.0,2017-07-26
11,BU1709,01120698,09:23:30,1,2638.0,4,105520.0,0,10.87,0.0,2017-07-26
12,MA709,01093723,09:29:56,1,2466.0,2,49320.0,0,4.12,0.0,2017-07-26
13,Y1801,10300647,09:31:06,0,6288.0,1,62880.0,0,2.58,0.0,2017-07-26
14,MA709,01112830,09:31:25,1,2467.0,2,49340.0,0,4.12,0.0,2017-07-26
15,Y1801,10317657,09:37:20,1,6284.0,1,62840.0,1,2.58,-40.0,2017-07-26
16,Y1801,10317786,09:37:22,1,6284.0,1,62840.0,1,2.58,-40.0,2017-07-26
17,C1709,10323154,09:39:28,1,1661.0,10,166100.0,0,12.37,0.0,2017-07-26
18,C1709,10341285,09:46:03,1,1661.0,5,83050.0,0,6.18,0.0,2017-07-26
19,C1709,10354121,09:55:14,1,1662.0,5,83100.0,0,6.18,0.0,2017-07-26
20,C1709,10372891,10:08:16,1,1663.0,5,83150.0,0,6.18,0.0,2017-07-26
21,BU1709,01446050,10:32:07,0,2636.0,3,79080.0,1,8.15,0.0,2017-07-26
22,MA709,01495658,10:36:08,0,2451.0,3,73530.0,1,18.54,570.0,2017-07-26
23,MA709,01496237,10:36:18,0,2451.0,2,49020.0,1,12.36,300.0,2017-07-26
24,MA709,01496238,10:36:18,0,2451.0,1,24510.0,1,6.18,160.0,2017-07-26
25,MA709,01496436,10:36:22,0,2451.0,1,24510.0,1,6.18,160.0,2017-07-26
26,BU1709,01499189,10:45:03,0,2634.0,5,131700.0,1,13.57,180.0,2017-07-26
27,C1709,10515696,14:09:42,0,1660.0,10,166000.0,1,0.01,100.0,2017-07-26
28,C1709,10517571,14:10:18,0,1659.0,5,82950.0,1,0.00,100.0,2017-07-26
29,C1709,10517846,14:10:24,0,1659.0,5,82950.0,1,0.00,150.0,2017-07-26
...,...,...,...,...,...,...,...,...,...,...,...
728,RB1801,01165666,09:22:56,0,3777.0,1,37770.0,1,3.89,-2200.0,2017-10-16
729,CS1801,10230579,09:43:17,1,1947.0,10,194700.0,0,15.46,0.0,2017-10-16
730,CS1801,10236506,09:46:39,1,1945.0,5,97250.0,0,7.73,0.0,2017-10-16
731,CS1801,10238771,09:49:44,1,1946.0,5,97300.0,0,7.73,0.0,2017-10-16
732,CF801,01104676,09:54:30,1,15180.0,1,75900.0,0,4.48,0.0,2017-10-16
733,M1801,10249044,09:57:49,0,2847.0,1,28470.0,0,1.55,0.0,2017-10-16
734,RM801,01123169,09:57:59,0,2269.0,1,22690.0,0,1.56,0.0,2017-10-16
735,RB1801,01359305,10:03:06,0,3785.0,1,37850.0,1,3.90,-2280.0,2017-10-16
736,JD1801,10276302,10:36:38,0,4274.0,1,42740.0,0,6.61,0.0,2017-10-16
737,JD1801,10276644,10:36:48,0,4270.0,1,42700.0,0,6.60,0.0,2017-10-16
738,JD1801,10277267,10:37:00,0,4268.0,1,42680.0,0,6.60,0.0,2017-10-16
739,JD1801,10278247,10:37:20,0,4267.0,1,42670.0,0,6.59,0.0,2017-10-16
740,JD1801,10281131,10:38:55,0,4263.0,1,42630.0,0,6.59,0.0,2017-10-16
741,M1801,10284642,10:41:23,0,2849.0,2,56980.0,0,3.09,0.0,2017-10-16
742,M1801,10284821,10:41:36,0,2849.0,1,28490.0,0,1.55,0.0,2017-10-16
743,RB1801,01482021,10:50:52,1,3788.0,1,37880.0,1,3.90,2190.0,2017-10-16
744,JD1801,10303103,11:01:56,1,4267.0,1,42670.0,1,6.59,-70.0,2017-10-16
745,RM801,01264174,11:04:01,0,2272.0,1,22720.0,0,1.56,0.0,2017-10-16
746,RB1801,01544076,11:04:15,1,3788.0,1,37880.0,1,3.90,2410.0,2017-10-16
747,RM801,01269583,11:06:30,0,2272.0,1,22720.0,0,1.56,0.0,2017-10-16
748,RM801,01276783,11:09:28,0,2273.0,1,22730.0,0,1.56,0.0,2017-10-16
749,ZN1712,01587288,11:10:41,0,26145.0,1,130725.0,0,3.10,0.0,2017-10-16
750,ZN1712,01621062,11:16:18,0,26140.0,1,130700.0,0,3.10,0.0,2017-10-16
751,ZN1712,01651462,11:20:29,1,26005.0,1,130025.0,1,0.01,-700.0,2017-10-16
752,ZN1712,01654166,11:21:01,1,25970.0,1,129850.0,1,0.01,-850.0,2017-10-16
753,JD1801,10388900,14:49:21,0,4277.0,1,42770.0,0,6.61,0.0,2017-10-16
754,CS1801,10393536,14:52:30,0,1946.0,15,291900.0,1,23.19,2420.0,2017-10-16
755,JD1801,10400160,14:57:05,1,4265.0,1,42650.0,1,6.59,-50.0,2017-10-16
756,CF801,01669132,14:57:57,0,15215.0,1,76075.0,1,4.48,1150.0,2017-10-16
757,CF801,01672726,14:58:19,0,15225.0,1,76125.0,1,4.48,-475.0,2017-10-16

In [5]:
df.index = df.real_trade_date 
df.index = pd.to_datetime(df.index)
df

,instrument,order_no,trade_time,direction,order_price,lots,turnover,open_close,fee,realized_pl,real_trade_date
real_trade_date,,,,,,,,,,,
2017-07-17,C1709,10397523,13:31:28,1,1670.0,5,83500.0,0,3.05,0.0,2017-07-17
2017-07-17,C1709,10424539,13:42:18,1,1669.0,3,50070.0,0,1.83,0.0,2017-07-17
2017-07-17,MA709,01736313,13:47:54,0,2502.0,1,25020.0,0,2.04,0.0,2017-07-17
2017-07-17,MA709,01736315,13:47:54,0,2502.0,2,50040.0,0,4.08,0.0,2017-07-17
2017-07-17,MA709,01743943,13:49:44,0,2501.0,2,50020.0,0,4.08,0.0,2017-07-17
2017-07-17,C1709,10438422,13:50:38,0,1673.0,8,133840.0,1,4.88,-270.0,2017-07-17
2017-07-17,L1709,30479260,13:52:29,0,9200.0,2,92000.0,0,4.08,0.0,2017-07-17
2017-07-17,RU1709,01716175,13:53:04,0,13560.0,1,135600.0,0,6.22,0.0,2017-07-17
2017-07-17,MA709,01772932,13:57:01,0,2501.0,3,75030.0,0,6.12,0.0,2017-07-17
2017-07-17,MA709,01791156,14:00:51,1,2496.0,1,24960.0,1,6.12,-60.0,2017-07-17
2017-07-17,RU1709,01769795,14:05:35,1,13515.0,1,135150.0,1,24.81,-450.0,2017-07-17
2017-07-17,MA709,01822370,14:06:07,1,2495.0,2,49900.0,1,12.24,-140.0,2017-07-17
2017-07-17,MA709,01822756,14:06:13,1,2495.0,2,49900.0,1,12.24,-120.0,2017-07-17
2017-07-17,L1709,30498397,14:07:10,1,9190.0,1,45950.0,1,2.04,-50.0,2017-07-17
2017-07-17,MA709,01838051,14:08:52,0,2496.0,1,24960.0,0,2.04,0.0,2017-07-17
2017-07-17,MA709,01838053,14:08:52,0,2496.0,3,74880.0,0,6.12,0.0,2017-07-17
2017-07-17,PP1709,30503055,14:11:09,0,8163.0,1,40815.0,0,5.00,0.0,2017-07-17
2017-07-17,PP1709,30503589,14:11:41,0,8164.0,1,40820.0,0,5.00,0.0,2017-07-17
2017-07-17,MA709,01870076,14:14:14,0,2496.0,3,74880.0,0,6.12,0.0,2017-07-17
2017-07-17,L1709,30507395,14:14:50,0,9215.0,1,46075.0,0,2.04,0.0,2017-07-17
2017-07-17,MA709,01895570,14:18:33,1,2491.0,3,74730.0,1,18.36,-300.0,2017-07-17
2017-07-17,MA709,01895571,14:18:33,1,2491.0,1,24910.0,1,6.12,-50.0,2017-07-17
2017-07-17,MA709,01895572,14:18:33,1,2491.0,3,74730.0,1,18.36,-150.0,2017-07-17
2017-07-17,MA709,01895573,14:18:33,1,2491.0,1,24910.0,1,6.12,-50.0,2017-07-17
2017-07-17,L1709,30516778,14:19:51,1,9195.0,2,91950.0,1,4.08,-125.0,2017-07-17
2017-07-17,MA709,01919216,14:21:37,0,2492.0,2,49840.0,0,4.08,0.0,2017-07-17
2017-07-17,MA709,01919218,14:21:37,0,2492.0,1,24920.0,0,2.04,0.0,2017-07-17
2017-07-17,MA709,01936405,14:23:20,0,2488.0,1,24880.0,0,2.04,0.0,2017-07-17
2017-07-17,PP1709,30523818,14:24:09,0,8161.0,1,40805.0,0,4.99,0.0,2017-07-17
2017-07-17,MA709,01953813,14:25:32,0,2488.0,1,24880.0,0,2.04,0.0,2017-07-17
...,...,...,...,...,...,...,...,...,...,...,...
2017-10-16,CS1801,10236507,09:46:39,1,1945.0,5,97250.0,0,7.65,0.0,2017-10-16
2017-10-16,CS1801,10238773,09:49:44,1,1946.0,1,19460.0,0,1.53,0.0,2017-10-16
2017-10-16,CS1801,10238774,09:49:44,1,1946.0,1,19460.0,0,1.53,0.0,2017-10-16
2017-10-16,CS1801,10238775,09:49:44,1,1946.0,3,58380.0,0,4.59,0.0,2017-10-16
2017-10-16,CF801,01104921,09:54:33,1,15180.0,1,75900.0,0,4.39,0.0,2017-10-16
2017-10-16,M1801,10249046,09:57:49,0,2847.0,1,28470.0,0,1.53,0.0,2017-10-16
2017-10-16,RM801,01123260,09:57:59,0,2269.0,1,22690.0,0,1.53,0.0,2017-10-16
2017-10-16,RB1801,01359307,10:03:06,0,3785.0,1,37850.0,1,3.86,-2280.0,2017-10-16
2017-10-16,JD1801,10276305,10:36:38,0,4274.0,1,42740.0,0,6.54,0.0,2017-10-16
2017-10-16,JD1801,10276646,10:36:48,0,4270.0,1,42700.0,0,6.53,0.0,2017-10-16
2017-10-16,JD1801,10277269,10:37:00,0,4268.0,1,42680.0,0,6.53,0.0,2017-10-16
2017-10-16,JD1801,10278248,10:37:20,0,4267.0,1,42670.0,0,6.53,0.0,2017-10-16
2017-10-16,JD1801,10281132,10:38:55,0,4263.0,1,42630.0,0,6.52,0.0,2017-10-16
2017-10-16,M1801,10284644,10:41:23,0,2849.0,2,56980.0,0,3.06,0.0,2017-10-16
2017-10-16,M1801,10284823,10:41:36,0,2849.0,1,28490.0,0,1.53,0.0,2017-10-16
2017-10-16,RB1801,01482022,10:50:52,1,3788.0,1,37880.0,1,3.86,2190.0,2017-10-16
2017-10-16,JD1801,10303185,11:02:05,1,4267.0,1,42670.0,1,6.53,-70.0,2017-10-16
2017-10-16,RM801,01264364,11:04:05,0,2272.0,1,22720.0,0,1.53,0.0,2017-10-16
2017-10-16,RB1801,01544078,11:04:15,1,3788.0,1,37880.0,1,3.86,2410.0,2017-10-16
2017-10-16,RM801,01269585,11:06:30,0,2272.0,1,22720.0,0,1.53,0.0,2017-10-16
2017-10-16,RM801,01276785,11:09:28,0,2273.0,1,22730.0,0,1.53,0.0,2017-10-16
2017-10-16,ZN1712,01587290,11:10:41,0,26145.0,1,130725.0,0,3.06,0.0,2017-10-16
2017-10-16,ZN1712,01621064,11:16:18,0,26140.0,1,130700.0,0,3.06,0.0,2017-10-16
2017-10-16,ZN1712,01651463,11:20:29,1,26005.0,1,130025.0,1,0.00,-700.0,2017-10-16
2017-10-16,ZN1712,01654172,11:21:01,1,25970.0,1,129850.0,1,0.00,-850.0,2017-10-16
2017-10-16,JD1801,10388902,14:49:21,0,4277.0,1,42770.0,0,6.54,0.0,2017-10-16
2017-10-16,CS1801,10393544,14:52:30,0,1946.0,15,291900.0,1,22.95,2420.0,2017-10-16
2017-10-16,JD1801,10400161,14:57:05,1,4265.0,1,42650.0,1,6.53,-50.0,2017-10-16
2017-10-16,CF801,01669138,14:57:57,0,15215.0,1,76075.0,1,4.39,1150.0,2017-10-16
2017-10-16,CF801,01672732,14:58:19,0,15225.0,1,76125.0,1,4.39,-475.0,2017-10-16

In [8]:
df2 = df.groupby([df.index.month, df.instrument]).apply(lambda x: x[x.order_price > 0])

In [9]:
df2

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18           A1709  10377969   13:33:37
                           2017-07-18           A1709  10390821   13:37:49
                           2017-07-18           A1709  10394856   13:39:12
                           2017-07-18           A1709  10524444   14:33:37
                           2017-07-18           A1709  10544194   14:51:59
                           2017-07-19           A1709  10152266   09:00:03
                           2017-07-19           A1709  10154367   09:00:08
                           2017-07-19           A1709  10164143   09:01:00
                           2017-07-19           A1709  10172018   09:02:09
                           2017-07-19           A1709  10181587   09:03:55
                           2017-07-19           A1709  10183730   09:04:26
                           2017-07-19           A1709  10201086   09:09:49
                           2017-07-19           A1709  10205254   09:10:41
                           2017-07-19           A1709  10205308   09:10:42
                           2017-07-19           A1709  10205344   09:10:42
                           2017-07-19           A1709  10374734   11:10:39
                           2017-07-19           A1709  10374735   11:10:39
                           2017-07-19           A1709  10374736   11:10:39
                           2017-07-19           A1709  10374737   11:10:39
                           2017-07-19           A1709  10374738   11:10:39
                           2017-07-19           A1709  10108816   22:24:33
                           2017-07-19           A1709  10110543   22:26:24
                           2017-07-19           A1709  10110979   22:27:16
                           2017-07-19           A1709  10114836   22:35:00
                           2017-07-19           A1709  10114837   22:35:00
                           2017-07-19           A1709  10115253   22:36:15
                           2017-07-19           A1709  10119235   22:40:08
                           2017-07-19           A1709  10120994   22:41:27
                           2017-07-19           A1709  10129496   22:56:06
                           2017-07-19           A1709  10131213   22:59:41
...                                               ...       ...        ...
10              TA801      2017-10-11           TA801  00571775   22:14:17
                           2017-10-11           TA801  00571776   22:14:17
                           2017-10-11           TA801  00631683   22:35:29
                           2017-10-11           TA801  00654826   22:44:11
                           2017-10-11           TA801  00709457   22:56:23
                           2017-10-12           TA801  01113266   10:40:21
                           2017-10-12           TA801  01197185   10:54:24
                           2017-10-12           TA801  01197862   10:54:29
                           2017-10-12           TA801  01295829   11:26:22
                           2017-10-12           TA801  00234719   21:21:14
                           2017-10-12           TA801  00234720   21:21:14
                           2017-10-12           TA801  00234721   21:21:14
                           2017-10-12           TA801  00234722   21:21:14
                           2017-10-12           TA801  00260990   21:23:56
                           2017-10-12           TA801  00260991   21:23:56
                           2017-10-12           TA801  00260994   21:23:56
                           2017-10-12           TA801  00260996   21:23:56
                           2017-10-12           TA801  00266223   21:24:25
                           2017-10-12           TA801  00266224   21:24:25
                           2017-10-12           TA801  00266225   21:24:25
                           2017-10-12           TA801  00266226   21:24:25
                           2017-10-12           TA801  00282245   21:28:30
                           2017-10-12           TA801  00283516   21:28:54
                           2017-10-12           TA801  00343036   21:38:42
                           2017-10-12           TA801  00343833   21:38:48
                           2017-10-12           TA801  00345587   21:39:03
                ZN1712     2017-10-16          ZN1712  01587290   11:10:41
                           2017-10-16          ZN1712  01621064   11:16:18
                           2017-10-16          ZN1712  01651463   11:20:29
                           2017-10-16          ZN1712  01654172   11:21:01

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18               1       3821.0     2
                           2017-07-18               1       3819.0     1
                           2017-07-18               1       3820.0     1
                           2017-07-18               1       3816.0     1
                           2017-07-18               0       3824.0     5
                           2017-07-19               1       3812.0     3
                           2017-07-19               1       3812.0     1
                           2017-07-19               0       3817.0     1
                           2017-07-19               0       3819.0     1
                           2017-07-19               0       3823.0     1
                           2017-07-19               0       3823.0     1
                           2017-07-19               1       3815.0     2
                           2017-07-19               1       3817.0     1
                           2017-07-19               1       3817.0     1
                           2017-07-19               1       3817.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               1       3820.0     2
                           2017-07-19               1       3821.0     1
                           2017-07-19               1       3823.0     2
                           2017-07-19               0       3824.0     1
                           2017-07-19               0       3824.0     1
                           2017-07-19               0       3824.0     1
                           2017-07-19               1       3821.0     2
                           2017-07-19               1       3822.0     2
                           2017-07-19               0       3823.0     2
                           2017-07-19               0       3824.0     2
...                                               ...          ...   ...
10              TA801      2017-10-11               0       5154.0     2
                           2017-10-11               0       5154.0     1
                           2017-10-11               1       5154.0     2
                           2017-10-11               0       5158.0     2
                           2017-10-11               0       5164.0     1
                           2017-10-12               1       5092.0     3
                           2017-10-12               0       5104.0     1
                           2017-10-12               0       5102.0     1
                           2017-10-12               0       5108.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5134.0     1
                           2017-10-12               0       5134.0     3
                           2017-10-12               0       5134.0     1
                           2017-10-12               0       5134.0     2
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     3
                           2017-10-12               0       5132.0     3
                           2017-10-12               1       5128.0     3
                           2017-10-12               1       5128.0     3
                           2017-10-12               0       5126.0     2
                           2017-10-12               0       5126.0     1
                           2017-10-12               0       5124.0     3
                ZN1712     2017-10-16               0      26145.0     1
                           2017-10-16               0      26140.0     1
                           2017-10-16               1      26005.0     1
                           2017-10-16               1      25970.0     1

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18        76420.0           0   4.08
                           2017-07-18        38190.0           0   2.04
                           2017-07-18        38200.0           0   2.04
                           2017-07-18        38160.0           0   2.04
                           2017-07-18       191200.0           1  10.20
                           2017-07-19       114360.0           0   6.12
                           2017-07-19        38120.0           0   2.04
                           2017-07-19        38170.0           1   2.04
                           2017-07-19        38190.0           1   2.04
                           2017-07-19        38230.0           1   2.04
                           2017-07-19        38230.0           1   2.04
                           2017-07-19        76300.0           0   4.08
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        76400.0           0   4.08
                           2017-07-19        38210.0           0   2.04
                           2017-07-19        76460.0           0   4.08
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        76420.0           0   4.08
                           2017-07-19        76440.0           0   4.08
                           2017-07-19        76460.0           1   4.08
                           2017-07-19        76480.0           1   4.08
...                                              ...         ...    ...
10              TA801      2017-10-11        51540.0           1   0.00
                           2017-10-11        25770.0           1   0.00
                           2017-10-11        51540.0           0   6.12
                           2017-10-11        51580.0           1   0.00
                           2017-10-11        25820.0           1   3.06
                           2017-10-12        76380.0           0   9.18
                           2017-10-12        25520.0           1   0.00
                           2017-10-12        25510.0           1   0.00
                           2017-10-12        25540.0           1   0.00
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        25670.0           1   3.06
                           2017-10-12        77010.0           1   9.18
                           2017-10-12        25670.0           1   3.06
                           2017-10-12        51340.0           1   6.12
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        76980.0           1   9.18
                           2017-10-12        76980.0           1   9.18
                           2017-10-12        76920.0           0   9.18
                           2017-10-12        76920.0           0   9.18
                           2017-10-12        51260.0           1   0.00
                           2017-10-12        25630.0           1   0.00
                           2017-10-12        76860.0           1   0.00
                ZN1712     2017-10-16       130725.0           0   3.06
                           2017-10-16       130700.0           0   3.06
                           2017-10-16       130025.0           1   0.00
                           2017-10-16       129850.0           1   0.00

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               A1709      2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18            -230.0      2017-07-18
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -50.0      2017-07-19
                           2017-07-19             -70.0      2017-07-19
                           2017-07-19            -110.0      2017-07-19
                           2017-07-19            -110.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19              10.0      2017-07-19
                           2017-07-19              10.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -40.0      2017-07-19
                           2017-07-19             -40.0      2017-07-19
                           2017-07-19             -30.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -60.0      2017-07-19
...                                                 ...             ...
10              TA801      2017-10-11            -180.0      2017-10-11
                           2017-10-11             -80.0      2017-10-11
                           2017-10-11               0.0      2017-10-11
                           2017-10-11            -200.0      2017-10-11
                           2017-10-11             -50.0      2017-10-11
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -60.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12             -80.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12             100.0      2017-10-12
                           2017-10-12              40.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12              20.0      2017-10-12
                           2017-10-12              40.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                           2017-10-12              80.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12             150.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12              20.0      2017-10-12
                           2017-10-12              10.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                ZN1712     2017-10-16               0.0      2017-10-16
                           2017-10-16               0.0      2017-10-16
                           2017-10-16            -700.0      2017-10-16
                           2017-10-16            -850.0      2017-10-16

[8061 rows x 11 columns]

In [10]:
df1.index = df1.real_trade_date 
df1.index = pd.to_datetime(df1.index)
df1

,instrument,order_no,trade_time,direction,order_price,lots,turnover,open_close,fee,realized_pl,real_trade_date
real_trade_date,,,,,,,,,,,
2017-07-26,MA709,00801137,09:02:09,0,2484.0,3,74520.0,0,6.18,0.0,2017-07-26
2017-07-26,MA709,00825297,09:04:23,0,2484.0,2,49680.0,0,4.12,0.0,2017-07-26
2017-07-26,Y1801,10235544,09:11:30,0,6288.0,1,62880.0,0,2.58,0.0,2017-07-26
2017-07-26,MA709,00962920,09:16:36,0,2481.0,3,74430.0,0,6.18,0.0,2017-07-26
2017-07-26,MA709,00974229,09:17:43,1,2477.0,1,24770.0,1,6.18,-70.0,2017-07-26
2017-07-26,MA709,00974231,09:17:43,1,2477.0,1,24770.0,1,6.18,-70.0,2017-07-26
2017-07-26,MA709,00974636,09:17:45,1,2476.0,1,24760.0,1,6.18,-80.0,2017-07-26
2017-07-26,MA709,00974637,09:17:45,1,2476.0,2,49520.0,1,12.36,-160.0,2017-07-26
2017-07-26,MA709,00974638,09:17:45,1,2476.0,3,74280.0,1,18.54,-150.0,2017-07-26
2017-07-26,MA709,01013830,09:21:19,1,2470.0,3,74100.0,0,6.18,0.0,2017-07-26
2017-07-26,BU1709,01113000,09:22:55,1,2636.0,4,105440.0,0,10.87,0.0,2017-07-26
2017-07-26,BU1709,01120698,09:23:30,1,2638.0,4,105520.0,0,10.87,0.0,2017-07-26
2017-07-26,MA709,01093723,09:29:56,1,2466.0,2,49320.0,0,4.12,0.0,2017-07-26
2017-07-26,Y1801,10300647,09:31:06,0,6288.0,1,62880.0,0,2.58,0.0,2017-07-26
2017-07-26,MA709,01112830,09:31:25,1,2467.0,2,49340.0,0,4.12,0.0,2017-07-26
2017-07-26,Y1801,10317657,09:37:20,1,6284.0,1,62840.0,1,2.58,-40.0,2017-07-26
2017-07-26,Y1801,10317786,09:37:22,1,6284.0,1,62840.0,1,2.58,-40.0,2017-07-26
2017-07-26,C1709,10323154,09:39:28,1,1661.0,10,166100.0,0,12.37,0.0,2017-07-26
2017-07-26,C1709,10341285,09:46:03,1,1661.0,5,83050.0,0,6.18,0.0,2017-07-26
2017-07-26,C1709,10354121,09:55:14,1,1662.0,5,83100.0,0,6.18,0.0,2017-07-26
2017-07-26,C1709,10372891,10:08:16,1,1663.0,5,83150.0,0,6.18,0.0,2017-07-26
2017-07-26,BU1709,01446050,10:32:07,0,2636.0,3,79080.0,1,8.15,0.0,2017-07-26
2017-07-26,MA709,01495658,10:36:08,0,2451.0,3,73530.0,1,18.54,570.0,2017-07-26
2017-07-26,MA709,01496237,10:36:18,0,2451.0,2,49020.0,1,12.36,300.0,2017-07-26
2017-07-26,MA709,01496238,10:36:18,0,2451.0,1,24510.0,1,6.18,160.0,2017-07-26
2017-07-26,MA709,01496436,10:36:22,0,2451.0,1,24510.0,1,6.18,160.0,2017-07-26
2017-07-26,BU1709,01499189,10:45:03,0,2634.0,5,131700.0,1,13.57,180.0,2017-07-26
2017-07-26,C1709,10515696,14:09:42,0,1660.0,10,166000.0,1,0.01,100.0,2017-07-26
2017-07-26,C1709,10517571,14:10:18,0,1659.0,5,82950.0,1,0.00,100.0,2017-07-26
2017-07-26,C1709,10517846,14:10:24,0,1659.0,5,82950.0,1,0.00,150.0,2017-07-26
...,...,...,...,...,...,...,...,...,...,...,...
2017-10-16,RB1801,01165666,09:22:56,0,3777.0,1,37770.0,1,3.89,-2200.0,2017-10-16
2017-10-16,CS1801,10230579,09:43:17,1,1947.0,10,194700.0,0,15.46,0.0,2017-10-16
2017-10-16,CS1801,10236506,09:46:39,1,1945.0,5,97250.0,0,7.73,0.0,2017-10-16
2017-10-16,CS1801,10238771,09:49:44,1,1946.0,5,97300.0,0,7.73,0.0,2017-10-16
2017-10-16,CF801,01104676,09:54:30,1,15180.0,1,75900.0,0,4.48,0.0,2017-10-16
2017-10-16,M1801,10249044,09:57:49,0,2847.0,1,28470.0,0,1.55,0.0,2017-10-16
2017-10-16,RM801,01123169,09:57:59,0,2269.0,1,22690.0,0,1.56,0.0,2017-10-16
2017-10-16,RB1801,01359305,10:03:06,0,3785.0,1,37850.0,1,3.90,-2280.0,2017-10-16
2017-10-16,JD1801,10276302,10:36:38,0,4274.0,1,42740.0,0,6.61,0.0,2017-10-16
2017-10-16,JD1801,10276644,10:36:48,0,4270.0,1,42700.0,0,6.60,0.0,2017-10-16
2017-10-16,JD1801,10277267,10:37:00,0,4268.0,1,42680.0,0,6.60,0.0,2017-10-16
2017-10-16,JD1801,10278247,10:37:20,0,4267.0,1,42670.0,0,6.59,0.0,2017-10-16
2017-10-16,JD1801,10281131,10:38:55,0,4263.0,1,42630.0,0,6.59,0.0,2017-10-16
2017-10-16,M1801,10284642,10:41:23,0,2849.0,2,56980.0,0,3.09,0.0,2017-10-16
2017-10-16,M1801,10284821,10:41:36,0,2849.0,1,28490.0,0,1.55,0.0,2017-10-16
2017-10-16,RB1801,01482021,10:50:52,1,3788.0,1,37880.0,1,3.90,2190.0,2017-10-16
2017-10-16,JD1801,10303103,11:01:56,1,4267.0,1,42670.0,1,6.59,-70.0,2017-10-16
2017-10-16,RM801,01264174,11:04:01,0,2272.0,1,22720.0,0,1.56,0.0,2017-10-16
2017-10-16,RB1801,01544076,11:04:15,1,3788.0,1,37880.0,1,3.90,2410.0,2017-10-16
2017-10-16,RM801,01269583,11:06:30,0,2272.0,1,22720.0,0,1.56,0.0,2017-10-16
2017-10-16,RM801,01276783,11:09:28,0,2273.0,1,22730.0,0,1.56,0.0,2017-10-16
2017-10-16,ZN1712,01587288,11:10:41,0,26145.0,1,130725.0,0,3.10,0.0,2017-10-16
2017-10-16,ZN1712,01621062,11:16:18,0,26140.0,1,130700.0,0,3.10,0.0,2017-10-16
2017-10-16,ZN1712,01651462,11:20:29,1,26005.0,1,130025.0,1,0.01,-700.0,2017-10-16
2017-10-16,ZN1712,01654166,11:21:01,1,25970.0,1,129850.0,1,0.01,-850.0,2017-10-16
2017-10-16,JD1801,10388900,14:49:21,0,4277.0,1,42770.0,0,6.61,0.0,2017-10-16
2017-10-16,CS1801,10393536,14:52:30,0,1946.0,15,291900.0,1,23.19,2420.0,2017-10-16
2017-10-16,JD1801,10400160,14:57:05,1,4265.0,1,42650.0,1,6.59,-50.0,2017-10-16
2017-10-16,CF801,01669132,14:57:57,0,15215.0,1,76075.0,1,4.48,1150.0,2017-10-16
2017-10-16,CF801,01672726,14:58:19,0,15225.0,1,76125.0,1,4.48,-475.0,2017-10-16

In [11]:
df3 = df1.groupby([df1.index.month, df1.instrument]).apply(lambda x: x[x.order_price > 0])
df3

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26           A1801  10522482   14:11:43
                           2017-07-26           A1801  10525471   14:12:49
                           2017-07-26           A1801  10537976   14:20:07
                           2017-07-27           A1801  10039313   21:08:04
                           2017-07-27           A1801  10052637   21:14:44
                           2017-07-27           A1801  10061137   21:20:02
                           2017-07-28           A1801  10644634   14:53:55
                           2017-07-28           A1801  10646282   14:54:39
                           2017-07-28           A1801  10652051   14:56:36
                           2017-07-28           A1801  10652236   14:56:42
                           2017-07-28           A1801  10662275   14:59:52
                           2017-07-28           A1801  10662276   14:59:52
                           2017-07-28           A1801  10002897   21:00:02
                           2017-07-28           A1801  10002899   21:00:02
                           2017-07-28           A1801  10002901   21:00:02
                           2017-07-28           A1801  10002902   21:00:02
                           2017-07-28           A1801  10017741   21:04:52
                           2017-07-28           A1801  10023936   21:08:10
                           2017-07-28           A1801  10023967   21:08:15
                           2017-07-28           A1801  10033875   21:15:59
                           2017-07-28           A1801  10105164   21:51:55
                           2017-07-28           A1801  10105170   21:51:55
                           2017-07-31           A1801  10265012   09:23:17
                           2017-07-31           A1801  10265169   09:23:18
                           2017-07-31           A1801  10266658   09:23:32
                           2017-07-31           A1801  10289953   09:34:16
                           2017-07-31           A1801  10516381   14:30:57
                           2017-07-31           A1801  10527557   14:37:42
                           2017-07-31           A1801  10536155   14:41:22
                           2017-07-31           A1801  10551855   14:48:44
...                                               ...       ...        ...
10              TA801      2017-10-11           TA801  00571802   22:14:17
                           2017-10-11           TA801  00571803   22:14:17
                           2017-10-11           TA801  00571804   22:14:17
                           2017-10-11           TA801  00571805   22:14:17
                           2017-10-11           TA801  00631677   22:35:29
                           2017-10-11           TA801  00654820   22:44:11
                           2017-10-11           TA801  00709449   22:56:23
                           2017-10-12           TA801  01113264   10:40:21
                           2017-10-12           TA801  01197172   10:54:24
                           2017-10-12           TA801  01197848   10:54:29
                           2017-10-12           TA801  01295823   11:26:22
                           2017-10-12           TA801  00234699   21:21:14
                           2017-10-12           TA801  00234701   21:21:14
                           2017-10-12           TA801  00260983   21:23:56
                           2017-10-12           TA801  00260985   21:23:56
                           2017-10-12           TA801  00260986   21:23:56
                           2017-10-12           TA801  00266212   21:24:25
                           2017-10-12           TA801  00266213   21:24:25
                           2017-10-12           TA801  00266214   21:24:25
                           2017-10-12           TA801  00266215   21:24:25
                           2017-10-12           TA801  00266216   21:24:25
                           2017-10-12           TA801  00282243   21:28:30
                           2017-10-12           TA801  00283136   21:28:48
                           2017-10-12           TA801  00343020   21:38:42
                           2017-10-12           TA801  00343827   21:38:48
                           2017-10-12           TA801  00345585   21:39:03
                ZN1712     2017-10-16          ZN1712  01587288   11:10:41
                           2017-10-16          ZN1712  01621062   11:16:18
                           2017-10-16          ZN1712  01651462   11:20:29
                           2017-10-16          ZN1712  01654166   11:21:01

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26               0       3859.0     2
                           2017-07-26               0       3858.0     3
                           2017-07-26               1       3845.0     5
                           2017-07-27               0       3856.0     3
                           2017-07-27               0       3853.0     1
                           2017-07-27               1       3845.0     4
                           2017-07-28               1       3846.0     2
                           2017-07-28               1       3847.0     1
                           2017-07-28               1       3848.0     2
                           2017-07-28               1       3849.0     5
                           2017-07-28               0       3853.0     4
                           2017-07-28               0       3854.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3871.0     2
                           2017-07-28               1       3866.0     2
                           2017-07-28               0       3867.0     1
                           2017-07-28               0       3867.0     2
                           2017-07-28               0       3866.0     2
                           2017-07-28               1       3869.0     4
                           2017-07-28               1       3869.0     4
                           2017-07-31               1       3846.0     2
                           2017-07-31               1       3846.0     1
                           2017-07-31               1       3848.0     1
                           2017-07-31               0       3855.0     2
                           2017-07-31               0       3856.0     2
                           2017-07-31               0       3867.0     2
                           2017-07-31               0       3872.0     3
                           2017-07-31               0       3867.0     1
...                                               ...          ...   ...
10              TA801      2017-10-11               0       5154.0     1
                           2017-10-11               0       5154.0     1
                           2017-10-11               0       5154.0     2
                           2017-10-11               0       5154.0     1
                           2017-10-11               1       5154.0     2
                           2017-10-11               0       5158.0     2
                           2017-10-11               0       5164.0     1
                           2017-10-12               1       5092.0     3
                           2017-10-12               0       5104.0     1
                           2017-10-12               0       5102.0     1
                           2017-10-12               0       5108.0     1
                           2017-10-12               0       5132.0     3
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5134.0     1
                           2017-10-12               0       5134.0     3
                           2017-10-12               0       5134.0     3
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     3
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     2
                           2017-10-12               1       5128.0     3
                           2017-10-12               1       5128.0     3
                           2017-10-12               0       5126.0     2
                           2017-10-12               0       5126.0     1
                           2017-10-12               0       5124.0     3
                ZN1712     2017-10-16               0      26145.0     1
                           2017-10-16               0      26140.0     1
                           2017-10-16               1      26005.0     1
                           2017-10-16               1      25970.0     1

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26        77180.0           0   4.12
                           2017-07-26       115740.0           0   6.19
                           2017-07-26       192250.0           1  10.31
                           2017-07-27       115680.0           0   6.19
                           2017-07-27        38530.0           0   2.06
                           2017-07-27       153800.0           1   8.25
                           2017-07-28        76920.0           0   4.12
                           2017-07-28        38470.0           0   2.06
                           2017-07-28        76960.0           0   4.12
                           2017-07-28       192450.0           0  10.31
                           2017-07-28       154120.0           1   8.25
                           2017-07-28        38540.0           1   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        77420.0           0   4.12
                           2017-07-28        77320.0           1   4.12
                           2017-07-28        38670.0           0   2.06
                           2017-07-28        77340.0           0   4.12
                           2017-07-28        77320.0           0   4.12
                           2017-07-28       154760.0           1   8.25
                           2017-07-28       154760.0           1   8.25
                           2017-07-31        76920.0           0   4.12
                           2017-07-31        38460.0           0   2.06
                           2017-07-31        38480.0           0   2.06
                           2017-07-31        77100.0           1   4.12
                           2017-07-31        77120.0           1   4.12
                           2017-07-31        77340.0           0   4.12
                           2017-07-31       116160.0           0   6.19
                           2017-07-31        38670.0           0   2.06
...                                              ...         ...    ...
10              TA801      2017-10-11        25770.0           1   0.00
                           2017-10-11        25770.0           1   0.00
                           2017-10-11        51540.0           1   0.00
                           2017-10-11        25770.0           1   0.00
                           2017-10-11        51540.0           0   6.18
                           2017-10-11        51580.0           1   0.00
                           2017-10-11        25820.0           1   3.09
                           2017-10-12        76380.0           0   9.27
                           2017-10-12        25520.0           1   0.00
                           2017-10-12        25510.0           1   0.00
                           2017-10-12        25540.0           1   0.00
                           2017-10-12        76980.0           1   9.27
                           2017-10-12        51320.0           1   6.18
                           2017-10-12        25670.0           1   3.09
                           2017-10-12        77010.0           1   9.27
                           2017-10-12        77010.0           1   9.27
                           2017-10-12        51320.0           1   6.18
                           2017-10-12        51320.0           1   6.18
                           2017-10-12        76980.0           1   9.27
                           2017-10-12        25660.0           1   3.09
                           2017-10-12        51320.0           1   6.18
                           2017-10-12        76920.0           0   9.27
                           2017-10-12        76920.0           0   9.27
                           2017-10-12        51260.0           1   0.00
                           2017-10-12        25630.0           1   0.00
                           2017-10-12        76860.0           1   0.00
                ZN1712     2017-10-16       130725.0           0   3.10
                           2017-10-16       130700.0           0   3.10
                           2017-10-16       130025.0           1   0.01
                           2017-10-16       129850.0           1   0.01

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               A1801      2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26            -670.0      2017-07-26
                           2017-07-27               0.0      2017-07-27
                           2017-07-27               0.0      2017-07-27
                           2017-07-27            -410.0      2017-07-27
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28            -250.0      2017-07-28
                           2017-07-28             -60.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28             -80.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28             -30.0      2017-07-28
                           2017-07-28             100.0      2017-07-28
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31            -180.0      2017-07-31
                           2017-07-31            -180.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
...                                                 ...             ...
10              TA801      2017-10-11            -100.0      2017-10-11
                           2017-10-11            -100.0      2017-10-11
                           2017-10-11            -180.0      2017-10-11
                           2017-10-11             -80.0      2017-10-11
                           2017-10-11               0.0      2017-10-11
                           2017-10-11            -200.0      2017-10-11
                           2017-10-11             -50.0      2017-10-11
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -60.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12             -80.0      2017-10-12
                           2017-10-12             210.0      2017-10-12
                           2017-10-12             100.0      2017-10-12
                           2017-10-12              40.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                           2017-10-12              80.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12              50.0      2017-10-12
                           2017-10-12             100.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12              20.0      2017-10-12
                           2017-10-12              10.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                ZN1712     2017-10-16               0.0      2017-10-16
                           2017-10-16               0.0      2017-10-16
                           2017-10-16            -700.0      2017-10-16
                           2017-10-16            -850.0      2017-10-16

[7141 rows x 11 columns]

In [12]:
df2

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18           A1709  10377969   13:33:37
                           2017-07-18           A1709  10390821   13:37:49
                           2017-07-18           A1709  10394856   13:39:12
                           2017-07-18           A1709  10524444   14:33:37
                           2017-07-18           A1709  10544194   14:51:59
                           2017-07-19           A1709  10152266   09:00:03
                           2017-07-19           A1709  10154367   09:00:08
                           2017-07-19           A1709  10164143   09:01:00
                           2017-07-19           A1709  10172018   09:02:09
                           2017-07-19           A1709  10181587   09:03:55
                           2017-07-19           A1709  10183730   09:04:26
                           2017-07-19           A1709  10201086   09:09:49
                           2017-07-19           A1709  10205254   09:10:41
                           2017-07-19           A1709  10205308   09:10:42
                           2017-07-19           A1709  10205344   09:10:42
                           2017-07-19           A1709  10374734   11:10:39
                           2017-07-19           A1709  10374735   11:10:39
                           2017-07-19           A1709  10374736   11:10:39
                           2017-07-19           A1709  10374737   11:10:39
                           2017-07-19           A1709  10374738   11:10:39
                           2017-07-19           A1709  10108816   22:24:33
                           2017-07-19           A1709  10110543   22:26:24
                           2017-07-19           A1709  10110979   22:27:16
                           2017-07-19           A1709  10114836   22:35:00
                           2017-07-19           A1709  10114837   22:35:00
                           2017-07-19           A1709  10115253   22:36:15
                           2017-07-19           A1709  10119235   22:40:08
                           2017-07-19           A1709  10120994   22:41:27
                           2017-07-19           A1709  10129496   22:56:06
                           2017-07-19           A1709  10131213   22:59:41
...                                               ...       ...        ...
10              TA801      2017-10-11           TA801  00571775   22:14:17
                           2017-10-11           TA801  00571776   22:14:17
                           2017-10-11           TA801  00631683   22:35:29
                           2017-10-11           TA801  00654826   22:44:11
                           2017-10-11           TA801  00709457   22:56:23
                           2017-10-12           TA801  01113266   10:40:21
                           2017-10-12           TA801  01197185   10:54:24
                           2017-10-12           TA801  01197862   10:54:29
                           2017-10-12           TA801  01295829   11:26:22
                           2017-10-12           TA801  00234719   21:21:14
                           2017-10-12           TA801  00234720   21:21:14
                           2017-10-12           TA801  00234721   21:21:14
                           2017-10-12           TA801  00234722   21:21:14
                           2017-10-12           TA801  00260990   21:23:56
                           2017-10-12           TA801  00260991   21:23:56
                           2017-10-12           TA801  00260994   21:23:56
                           2017-10-12           TA801  00260996   21:23:56
                           2017-10-12           TA801  00266223   21:24:25
                           2017-10-12           TA801  00266224   21:24:25
                           2017-10-12           TA801  00266225   21:24:25
                           2017-10-12           TA801  00266226   21:24:25
                           2017-10-12           TA801  00282245   21:28:30
                           2017-10-12           TA801  00283516   21:28:54
                           2017-10-12           TA801  00343036   21:38:42
                           2017-10-12           TA801  00343833   21:38:48
                           2017-10-12           TA801  00345587   21:39:03
                ZN1712     2017-10-16          ZN1712  01587290   11:10:41
                           2017-10-16          ZN1712  01621064   11:16:18
                           2017-10-16          ZN1712  01651463   11:20:29
                           2017-10-16          ZN1712  01654172   11:21:01

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18               1       3821.0     2
                           2017-07-18               1       3819.0     1
                           2017-07-18               1       3820.0     1
                           2017-07-18               1       3816.0     1
                           2017-07-18               0       3824.0     5
                           2017-07-19               1       3812.0     3
                           2017-07-19               1       3812.0     1
                           2017-07-19               0       3817.0     1
                           2017-07-19               0       3819.0     1
                           2017-07-19               0       3823.0     1
                           2017-07-19               0       3823.0     1
                           2017-07-19               1       3815.0     2
                           2017-07-19               1       3817.0     1
                           2017-07-19               1       3817.0     1
                           2017-07-19               1       3817.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               0       3814.0     1
                           2017-07-19               1       3820.0     2
                           2017-07-19               1       3821.0     1
                           2017-07-19               1       3823.0     2
                           2017-07-19               0       3824.0     1
                           2017-07-19               0       3824.0     1
                           2017-07-19               0       3824.0     1
                           2017-07-19               1       3821.0     2
                           2017-07-19               1       3822.0     2
                           2017-07-19               0       3823.0     2
                           2017-07-19               0       3824.0     2
...                                               ...          ...   ...
10              TA801      2017-10-11               0       5154.0     2
                           2017-10-11               0       5154.0     1
                           2017-10-11               1       5154.0     2
                           2017-10-11               0       5158.0     2
                           2017-10-11               0       5164.0     1
                           2017-10-12               1       5092.0     3
                           2017-10-12               0       5104.0     1
                           2017-10-12               0       5102.0     1
                           2017-10-12               0       5108.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     1
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5134.0     1
                           2017-10-12               0       5134.0     3
                           2017-10-12               0       5134.0     1
                           2017-10-12               0       5134.0     2
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     2
                           2017-10-12               0       5132.0     3
                           2017-10-12               0       5132.0     3
                           2017-10-12               1       5128.0     3
                           2017-10-12               1       5128.0     3
                           2017-10-12               0       5126.0     2
                           2017-10-12               0       5126.0     1
                           2017-10-12               0       5124.0     3
                ZN1712     2017-10-16               0      26145.0     1
                           2017-10-16               0      26140.0     1
                           2017-10-16               1      26005.0     1
                           2017-10-16               1      25970.0     1

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               A1709      2017-07-18        76420.0           0   4.08
                           2017-07-18        38190.0           0   2.04
                           2017-07-18        38200.0           0   2.04
                           2017-07-18        38160.0           0   2.04
                           2017-07-18       191200.0           1  10.20
                           2017-07-19       114360.0           0   6.12
                           2017-07-19        38120.0           0   2.04
                           2017-07-19        38170.0           1   2.04
                           2017-07-19        38190.0           1   2.04
                           2017-07-19        38230.0           1   2.04
                           2017-07-19        38230.0           1   2.04
                           2017-07-19        76300.0           0   4.08
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38170.0           0   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        38140.0           1   2.04
                           2017-07-19        76400.0           0   4.08
                           2017-07-19        38210.0           0   2.04
                           2017-07-19        76460.0           0   4.08
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        38240.0           1   2.04
                           2017-07-19        76420.0           0   4.08
                           2017-07-19        76440.0           0   4.08
                           2017-07-19        76460.0           1   4.08
                           2017-07-19        76480.0           1   4.08
...                                              ...         ...    ...
10              TA801      2017-10-11        51540.0           1   0.00
                           2017-10-11        25770.0           1   0.00
                           2017-10-11        51540.0           0   6.12
                           2017-10-11        51580.0           1   0.00
                           2017-10-11        25820.0           1   3.06
                           2017-10-12        76380.0           0   9.18
                           2017-10-12        25520.0           1   0.00
                           2017-10-12        25510.0           1   0.00
                           2017-10-12        25540.0           1   0.00
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        25660.0           1   3.06
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        25670.0           1   3.06
                           2017-10-12        77010.0           1   9.18
                           2017-10-12        25670.0           1   3.06
                           2017-10-12        51340.0           1   6.12
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        51320.0           1   6.12
                           2017-10-12        76980.0           1   9.18
                           2017-10-12        76980.0           1   9.18
                           2017-10-12        76920.0           0   9.18
                           2017-10-12        76920.0           0   9.18
                           2017-10-12        51260.0           1   0.00
                           2017-10-12        25630.0           1   0.00
                           2017-10-12        76860.0           1   0.00
                ZN1712     2017-10-16       130725.0           0   3.06
                           2017-10-16       130700.0           0   3.06
                           2017-10-16       130025.0           1   0.00
                           2017-10-16       129850.0           1   0.00

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               A1709      2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18               0.0      2017-07-18
                           2017-07-18            -230.0      2017-07-18
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -50.0      2017-07-19
                           2017-07-19             -70.0      2017-07-19
                           2017-07-19            -110.0      2017-07-19
                           2017-07-19            -110.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19              10.0      2017-07-19
                           2017-07-19              10.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19              30.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -40.0      2017-07-19
                           2017-07-19             -40.0      2017-07-19
                           2017-07-19             -30.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19               0.0      2017-07-19
                           2017-07-19             -60.0      2017-07-19
...                                                 ...             ...
10              TA801      2017-10-11            -180.0      2017-10-11
                           2017-10-11             -80.0      2017-10-11
                           2017-10-11               0.0      2017-10-11
                           2017-10-11            -200.0      2017-10-11
                           2017-10-11             -50.0      2017-10-11
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -60.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12             -80.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12              70.0      2017-10-12
                           2017-10-12             100.0      2017-10-12
                           2017-10-12              40.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12              20.0      2017-10-12
                           2017-10-12              40.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                           2017-10-12              80.0      2017-10-12
                           2017-10-12             120.0      2017-10-12
                           2017-10-12             150.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12              20.0      2017-10-12
                           2017-10-12              10.0      2017-10-12
                           2017-10-12              60.0      2017-10-12
                ZN1712     2017-10-16               0.0      2017-10-16
                           2017-10-16               0.0      2017-10-16
                           2017-10-16            -700.0      2017-10-16
                           2017-10-16            -850.0      2017-10-16

[8061 rows x 11 columns]

In [16]:
df2[df2.instrument == 'A1801' ]

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-21           A1801  10475163   11:29:30
                           2017-07-21           A1801  10481759   13:32:20
                           2017-07-21           A1801  10502527   13:41:47
                           2017-07-21           A1801  10588162   14:39:55
                           2017-07-21           A1801  10588730   14:40:33
                           2017-07-21           A1801  10055621   21:11:18
                           2017-07-21           A1801  10067252   21:17:36
                           2017-07-21           A1801  10075978   21:23:53
                           2017-07-21           A1801  10080170   21:26:06
                           2017-07-21           A1801  10101371   21:43:19
                           2017-07-21           A1801  10115135   21:52:01
                           2017-07-21           A1801  10189166   23:11:35
                           2017-07-21           A1801  10189167   23:11:35
                           2017-07-21           A1801  10189168   23:11:35
                           2017-07-21           A1801  10192816   23:12:22
                           2017-07-24           A1801  10022540   21:11:24
                           2017-07-24           A1801  10048652   21:40:54
                           2017-07-24           A1801  10056871   21:48:08
                           2017-07-24           A1801  10058596   21:50:56
                           2017-07-24           A1801  10073321   22:04:29
                           2017-07-24           A1801  10074376   22:04:45
                           2017-07-24           A1801  10079204   22:08:31
                           2017-07-24           A1801  10085387   22:16:14
                           2017-07-24           A1801  10090707   22:22:01
                           2017-07-24           A1801  10091413   22:22:19
                           2017-07-24           A1801  10091414   22:22:19
                           2017-07-26           A1801  10522425   14:11:41
                           2017-07-26           A1801  10522427   14:11:41
                           2017-07-26           A1801  10522927   14:11:48
                           2017-07-26           A1801  10537977   14:20:07
...                                               ...       ...        ...
9               A1801      2017-09-19           A1801  10005298   21:00:45
                           2017-09-19           A1801  10005299   21:00:45
                           2017-09-19           A1801  10005376   21:00:46
                           2017-09-19           A1801  10013948   21:04:04
                           2017-09-19           A1801  10015102   21:04:45
                           2017-09-19           A1801  10017377   21:06:19
                           2017-09-19           A1801  10020402   21:09:00
                           2017-09-19           A1801  10022725   21:12:05
                           2017-09-19           A1801  10022726   21:12:05
                           2017-09-19           A1801  10022728   21:12:05
                           2017-09-19           A1801  10022729   21:12:05
                           2017-09-19           A1801  10023351   21:12:18
10              A1801      2017-10-12           A1801  10065940   09:00:00
                           2017-10-12           A1801  10071267   09:01:30
                           2017-10-12           A1801  10088753   09:08:08
                           2017-10-12           A1801  10092375   09:10:25
                           2017-10-12           A1801  10093026   09:10:40
                           2017-10-12           A1801  10103800   09:22:02
                           2017-10-12           A1801  10113240   09:33:09
                           2017-10-12           A1801  10122954   09:48:31
                           2017-10-12           A1801  10126060   09:55:38
                           2017-10-12           A1801  10133547   10:02:17
                           2017-10-12           A1801  10141174   10:12:34
                           2017-10-12           A1801  10143713   10:14:54
                           2017-10-12           A1801  10144227   10:30:02
                           2017-10-12           A1801  10146466   10:32:48
                           2017-10-12           A1801  10146467   10:32:48
                           2017-10-12           A1801  10146515   10:32:49
                           2017-10-12           A1801  10146555   10:32:53
                           2017-10-12           A1801  10146565   10:32:54

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-21               0       3862.0     2
                           2017-07-21               0       3866.0     2
                           2017-07-21               0       3866.0     1
                           2017-07-21               0       3867.0     1
                           2017-07-21               0       3866.0     1
                           2017-07-21               0       3873.0     2
                           2017-07-21               0       3878.0     1
                           2017-07-21               0       3877.0     1
                           2017-07-21               0       3874.0     1
                           2017-07-21               0       3873.0     1
                           2017-07-21               0       3872.0     1
                           2017-07-21               1       3868.0     3
                           2017-07-21               1       3868.0     1
                           2017-07-21               1       3868.0     1
                           2017-07-21               1       3862.0     2
                           2017-07-24               0       3876.0     1
                           2017-07-24               1       3869.0     2
                           2017-07-24               0       3870.0     1
                           2017-07-24               0       3870.0     1
                           2017-07-24               1       3866.0     2
                           2017-07-24               1       3864.0     3
                           2017-07-24               0       3867.0     3
                           2017-07-24               0       3868.0     1
                           2017-07-24               1       3862.0     4
                           2017-07-24               1       3859.0     1
                           2017-07-24               1       3858.0     2
                           2017-07-26               0       3859.0     1
                           2017-07-26               0       3859.0     1
                           2017-07-26               0       3858.0     3
                           2017-07-26               1       3845.0     1
...                                               ...          ...   ...
9               A1801      2017-09-19               1       3809.0     2
                           2017-09-19               1       3809.0     1
                           2017-09-19               1       3810.0     3
                           2017-09-19               1       3811.0     1
                           2017-09-19               1       3813.0     1
                           2017-09-19               1       3812.0     1
                           2017-09-19               1       3812.0     1
                           2017-09-19               0       3817.0     1
                           2017-09-19               0       3817.0     1
                           2017-09-19               0       3817.0     2
                           2017-09-19               0       3817.0     1
                           2017-09-19               0       3817.0     5
10              A1801      2017-10-12               0       3850.0     4
                           2017-10-12               0       3850.0     1
                           2017-10-12               1       3846.0     1
                           2017-10-12               1       3843.0     1
                           2017-10-12               1       3845.0     1
                           2017-10-12               0       3846.0     1
                           2017-10-12               1       3841.0     1
                           2017-10-12               0       3840.0     1
                           2017-10-12               0       3841.0     1
                           2017-10-12               0       3840.0     1
                           2017-10-12               1       3839.0     1
                           2017-10-12               0       3843.0     1
                           2017-10-12               0       3843.0     1
                           2017-10-12               1       3838.0     1
                           2017-10-12               1       3838.0     1
                           2017-10-12               1       3838.0     2
                           2017-10-12               1       3839.0     1
                           2017-10-12               1       3839.0     1

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-21        77240.0           0   4.08
                           2017-07-21        77320.0           0   4.08
                           2017-07-21        38660.0           0   2.04
                           2017-07-21        38670.0           0   2.04
                           2017-07-21        38660.0           0   2.04
                           2017-07-21        77460.0           0   4.08
                           2017-07-21        38780.0           0   2.04
                           2017-07-21        38770.0           0   2.04
                           2017-07-21        38740.0           0   2.04
                           2017-07-21        38730.0           0   2.04
                           2017-07-21        38720.0           0   2.04
                           2017-07-21       116040.0           1   6.12
                           2017-07-21        38680.0           1   2.04
                           2017-07-21        38680.0           1   2.04
                           2017-07-21        77240.0           1   4.08
                           2017-07-24        38760.0           0   2.04
                           2017-07-24        77380.0           1   4.08
                           2017-07-24        38700.0           0   2.04
                           2017-07-24        38700.0           0   2.04
                           2017-07-24        77320.0           1   4.08
                           2017-07-24       115920.0           1   6.12
                           2017-07-24       116010.0           0   6.12
                           2017-07-24        38680.0           0   2.04
                           2017-07-24       154480.0           1   8.16
                           2017-07-24        38590.0           1   2.04
                           2017-07-24        77160.0           1   4.08
                           2017-07-26        38590.0           0   2.04
                           2017-07-26        38590.0           0   2.04
                           2017-07-26       115740.0           0   6.12
                           2017-07-26        38450.0           1   2.04
...                                              ...         ...    ...
9               A1801      2017-09-19        76180.0           0   4.08
                           2017-09-19        38090.0           0   2.04
                           2017-09-19       114300.0           0   6.12
                           2017-09-19        38110.0           0   2.04
                           2017-09-19        38130.0           0   2.04
                           2017-09-19        38120.0           0   2.04
                           2017-09-19        38120.0           0   2.04
                           2017-09-19        38170.0           1   2.04
                           2017-09-19        38170.0           1   2.04
                           2017-09-19        76340.0           1   4.08
                           2017-09-19        38170.0           1   2.04
                           2017-09-19       190850.0           1  10.20
10              A1801      2017-10-12       154000.0           0   8.16
                           2017-10-12        38500.0           0   2.04
                           2017-10-12        38460.0           1   2.04
                           2017-10-12        38430.0           1   2.04
                           2017-10-12        38450.0           1   2.04
                           2017-10-12        38460.0           0   2.04
                           2017-10-12        38410.0           1   2.04
                           2017-10-12        38400.0           0   2.04
                           2017-10-12        38410.0           0   2.04
                           2017-10-12        38400.0           0   2.04
                           2017-10-12        38390.0           1   2.04
                           2017-10-12        38430.0           0   2.04
                           2017-10-12        38430.0           0   2.04
                           2017-10-12        38380.0           1   2.04
                           2017-10-12        38380.0           1   2.04
                           2017-10-12        76760.0           1   4.08
                           2017-10-12        38390.0           1   2.04
                           2017-10-12        38390.0           1   2.04

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               A1801      2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21               0.0      2017-07-21
                           2017-07-21            -200.0      2017-07-21
                           2017-07-21             -90.0      2017-07-21
                           2017-07-21             -60.0      2017-07-21
                           2017-07-21            -210.0      2017-07-21
                           2017-07-24               0.0      2017-07-24
                           2017-07-24             140.0      2017-07-24
                           2017-07-24               0.0      2017-07-24
                           2017-07-24               0.0      2017-07-24
                           2017-07-24               0.0      2017-07-24
                           2017-07-24             -70.0      2017-07-24
                           2017-07-24               0.0      2017-07-24
                           2017-07-24               0.0      2017-07-24
                           2017-07-24            -350.0      2017-07-24
                           2017-07-24             -80.0      2017-07-24
                           2017-07-24            -190.0      2017-07-24
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26            -140.0      2017-07-26
...                                                 ...             ...
9               A1801      2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19             -80.0      2017-09-19
                           2017-09-19             -80.0      2017-09-19
                           2017-09-19            -150.0      2017-09-19
                           2017-09-19             -70.0      2017-09-19
                           2017-09-19            -270.0      2017-09-19
10              A1801      2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -40.0      2017-10-12
                           2017-10-12             -70.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -90.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12            -110.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -80.0      2017-10-12
                           2017-10-12             -20.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12             -40.0      2017-10-12
                           2017-10-12             -40.0      2017-10-12

[329 rows x 11 columns]

In [17]:
df3[df3.instrument ==  'A1801']

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26           A1801  10522482   14:11:43
                           2017-07-26           A1801  10525471   14:12:49
                           2017-07-26           A1801  10537976   14:20:07
                           2017-07-27           A1801  10039313   21:08:04
                           2017-07-27           A1801  10052637   21:14:44
                           2017-07-27           A1801  10061137   21:20:02
                           2017-07-28           A1801  10644634   14:53:55
                           2017-07-28           A1801  10646282   14:54:39
                           2017-07-28           A1801  10652051   14:56:36
                           2017-07-28           A1801  10652236   14:56:42
                           2017-07-28           A1801  10662275   14:59:52
                           2017-07-28           A1801  10662276   14:59:52
                           2017-07-28           A1801  10002897   21:00:02
                           2017-07-28           A1801  10002899   21:00:02
                           2017-07-28           A1801  10002901   21:00:02
                           2017-07-28           A1801  10002902   21:00:02
                           2017-07-28           A1801  10017741   21:04:52
                           2017-07-28           A1801  10023936   21:08:10
                           2017-07-28           A1801  10023967   21:08:15
                           2017-07-28           A1801  10033875   21:15:59
                           2017-07-28           A1801  10105164   21:51:55
                           2017-07-28           A1801  10105170   21:51:55
                           2017-07-31           A1801  10265012   09:23:17
                           2017-07-31           A1801  10265169   09:23:18
                           2017-07-31           A1801  10266658   09:23:32
                           2017-07-31           A1801  10289953   09:34:16
                           2017-07-31           A1801  10516381   14:30:57
                           2017-07-31           A1801  10527557   14:37:42
                           2017-07-31           A1801  10536155   14:41:22
                           2017-07-31           A1801  10551855   14:48:44
...                                               ...       ...        ...
9               A1801      2017-09-19           A1801  10337084   13:49:30
                           2017-09-19           A1801  10337085   13:49:30
                           2017-09-19           A1801  10339200   13:53:02
                           2017-09-19           A1801  10005295   21:00:45
                           2017-09-19           A1801  10005296   21:00:45
                           2017-09-19           A1801  10005374   21:00:46
                           2017-09-19           A1801  10013947   21:04:04
                           2017-09-19           A1801  10015100   21:04:45
                           2017-09-19           A1801  10017376   21:06:19
                           2017-09-19           A1801  10020401   21:09:00
                           2017-09-19           A1801  10022722   21:12:05
                           2017-09-19           A1801  10022723   21:12:05
                           2017-09-19           A1801  10022724   21:12:05
                           2017-09-19           A1801  10023350   21:12:18
10              A1801      2017-10-12           A1801  10065926   09:00:00
                           2017-10-12           A1801  10071264   09:01:30
                           2017-10-12           A1801  10088748   09:08:08
                           2017-10-12           A1801  10092373   09:10:25
                           2017-10-12           A1801  10093025   09:10:40
                           2017-10-12           A1801  10103796   09:22:02
                           2017-10-12           A1801  10113238   09:33:09
                           2017-10-12           A1801  10122952   09:48:31
                           2017-10-12           A1801  10126057   09:55:38
                           2017-10-12           A1801  10133545   10:02:17
                           2017-10-12           A1801  10141172   10:12:34
                           2017-10-12           A1801  10143710   10:14:54
                           2017-10-12           A1801  10144225   10:30:02
                           2017-10-12           A1801  10146464   10:32:47
                           2017-10-12           A1801  10146512   10:32:49
                           2017-10-12           A1801  10146552   10:32:53

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26               0       3859.0     2
                           2017-07-26               0       3858.0     3
                           2017-07-26               1       3845.0     5
                           2017-07-27               0       3856.0     3
                           2017-07-27               0       3853.0     1
                           2017-07-27               1       3845.0     4
                           2017-07-28               1       3846.0     2
                           2017-07-28               1       3847.0     1
                           2017-07-28               1       3848.0     2
                           2017-07-28               1       3849.0     5
                           2017-07-28               0       3853.0     4
                           2017-07-28               0       3854.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3870.0     1
                           2017-07-28               0       3871.0     2
                           2017-07-28               1       3866.0     2
                           2017-07-28               0       3867.0     1
                           2017-07-28               0       3867.0     2
                           2017-07-28               0       3866.0     2
                           2017-07-28               1       3869.0     4
                           2017-07-28               1       3869.0     4
                           2017-07-31               1       3846.0     2
                           2017-07-31               1       3846.0     1
                           2017-07-31               1       3848.0     1
                           2017-07-31               0       3855.0     2
                           2017-07-31               0       3856.0     2
                           2017-07-31               0       3867.0     2
                           2017-07-31               0       3872.0     3
                           2017-07-31               0       3867.0     1
...                                               ...          ...   ...
9               A1801      2017-09-19               0       3815.0     1
                           2017-09-19               0       3815.0     1
                           2017-09-19               0       3817.0     3
                           2017-09-19               1       3809.0     2
                           2017-09-19               1       3809.0     1
                           2017-09-19               1       3810.0     3
                           2017-09-19               1       3811.0     1
                           2017-09-19               1       3813.0     1
                           2017-09-19               1       3812.0     1
                           2017-09-19               1       3812.0     1
                           2017-09-19               0       3817.0     3
                           2017-09-19               0       3817.0     1
                           2017-09-19               0       3817.0     1
                           2017-09-19               0       3817.0     5
10              A1801      2017-10-12               0       3850.0     4
                           2017-10-12               0       3850.0     1
                           2017-10-12               1       3846.0     1
                           2017-10-12               1       3843.0     1
                           2017-10-12               1       3845.0     1
                           2017-10-12               0       3846.0     1
                           2017-10-12               1       3841.0     1
                           2017-10-12               0       3840.0     1
                           2017-10-12               0       3841.0     1
                           2017-10-12               0       3840.0     1
                           2017-10-12               1       3839.0     1
                           2017-10-12               0       3843.0     1
                           2017-10-12               0       3843.0     1
                           2017-10-12               1       3838.0     2
                           2017-10-12               1       3838.0     2
                           2017-10-12               1       3839.0     2

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               A1801      2017-07-26        77180.0           0   4.12
                           2017-07-26       115740.0           0   6.19
                           2017-07-26       192250.0           1  10.31
                           2017-07-27       115680.0           0   6.19
                           2017-07-27        38530.0           0   2.06
                           2017-07-27       153800.0           1   8.25
                           2017-07-28        76920.0           0   4.12
                           2017-07-28        38470.0           0   2.06
                           2017-07-28        76960.0           0   4.12
                           2017-07-28       192450.0           0  10.31
                           2017-07-28       154120.0           1   8.25
                           2017-07-28        38540.0           1   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        38700.0           0   2.06
                           2017-07-28        77420.0           0   4.12
                           2017-07-28        77320.0           1   4.12
                           2017-07-28        38670.0           0   2.06
                           2017-07-28        77340.0           0   4.12
                           2017-07-28        77320.0           0   4.12
                           2017-07-28       154760.0           1   8.25
                           2017-07-28       154760.0           1   8.25
                           2017-07-31        76920.0           0   4.12
                           2017-07-31        38460.0           0   2.06
                           2017-07-31        38480.0           0   2.06
                           2017-07-31        77100.0           1   4.12
                           2017-07-31        77120.0           1   4.12
                           2017-07-31        77340.0           0   4.12
                           2017-07-31       116160.0           0   6.19
                           2017-07-31        38670.0           0   2.06
...                                              ...         ...    ...
9               A1801      2017-09-19        38150.0           1   2.06
                           2017-09-19        38150.0           1   2.06
                           2017-09-19       114510.0           1   6.19
                           2017-09-19        76180.0           0   4.12
                           2017-09-19        38090.0           0   2.06
                           2017-09-19       114300.0           0   6.19
                           2017-09-19        38110.0           0   2.06
                           2017-09-19        38130.0           0   2.06
                           2017-09-19        38120.0           0   2.06
                           2017-09-19        38120.0           0   2.06
                           2017-09-19       114510.0           1   6.19
                           2017-09-19        38170.0           1   2.06
                           2017-09-19        38170.0           1   2.06
                           2017-09-19       190850.0           1  10.31
10              A1801      2017-10-12       154000.0           0   8.25
                           2017-10-12        38500.0           0   2.06
                           2017-10-12        38460.0           1   2.06
                           2017-10-12        38430.0           1   2.06
                           2017-10-12        38450.0           1   2.06
                           2017-10-12        38460.0           0   2.06
                           2017-10-12        38410.0           1   2.06
                           2017-10-12        38400.0           0   2.06
                           2017-10-12        38410.0           0   2.06
                           2017-10-12        38400.0           0   2.06
                           2017-10-12        38390.0           1   2.06
                           2017-10-12        38430.0           0   2.06
                           2017-10-12        38430.0           0   2.06
                           2017-10-12        76760.0           1   4.12
                           2017-10-12        76760.0           1   4.12
                           2017-10-12        76780.0           1   4.12

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               A1801      2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26            -670.0      2017-07-26
                           2017-07-27               0.0      2017-07-27
                           2017-07-27               0.0      2017-07-27
                           2017-07-27            -410.0      2017-07-27
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28            -250.0      2017-07-28
                           2017-07-28             -60.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28             -80.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28               0.0      2017-07-28
                           2017-07-28             -30.0      2017-07-28
                           2017-07-28             100.0      2017-07-28
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31            -180.0      2017-07-31
                           2017-07-31            -180.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
                           2017-07-31               0.0      2017-07-31
...                                                 ...             ...
9               A1801      2017-09-19              20.0      2017-09-19
                           2017-09-19             -30.0      2017-09-19
                           2017-09-19            -100.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19               0.0      2017-09-19
                           2017-09-19            -240.0      2017-09-19
                           2017-09-19             -70.0      2017-09-19
                           2017-09-19             -70.0      2017-09-19
                           2017-09-19            -270.0      2017-09-19
10              A1801      2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -40.0      2017-10-12
                           2017-10-12             -70.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12             -90.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12            -110.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12               0.0      2017-10-12
                           2017-10-12            -100.0      2017-10-12
                           2017-10-12             -50.0      2017-10-12
                           2017-10-12             -80.0      2017-10-12

[295 rows x 11 columns]

In [18]:
df2[df2.instrument == 'MA709']

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-17           MA709  01736313   13:47:54
                           2017-07-17           MA709  01736315   13:47:54
                           2017-07-17           MA709  01743943   13:49:44
                           2017-07-17           MA709  01772932   13:57:01
                           2017-07-17           MA709  01791156   14:00:51
                           2017-07-17           MA709  01822370   14:06:07
                           2017-07-17           MA709  01822756   14:06:13
                           2017-07-17           MA709  01838051   14:08:52
                           2017-07-17           MA709  01838053   14:08:52
                           2017-07-17           MA709  01870076   14:14:14
                           2017-07-17           MA709  01895570   14:18:33
                           2017-07-17           MA709  01895571   14:18:33
                           2017-07-17           MA709  01895572   14:18:33
                           2017-07-17           MA709  01895573   14:18:33
                           2017-07-17           MA709  01919216   14:21:37
                           2017-07-17           MA709  01919218   14:21:37
                           2017-07-17           MA709  01936405   14:23:20
                           2017-07-17           MA709  01953813   14:25:32
                           2017-07-17           MA709  01958814   14:26:10
                           2017-07-17           MA709  02056679   14:40:28
                           2017-07-17           MA709  02066956   14:41:47
                           2017-07-17           MA709  02101156   14:45:36
                           2017-07-17           MA709  02107120   14:46:39
                           2017-07-17           MA709  02129739   14:50:58
                           2017-07-17           MA709  02129741   14:50:58
                           2017-07-17           MA709  02129743   14:50:58
                           2017-07-17           MA709  02129745   14:50:58
                           2017-07-17           MA709  02129747   14:50:58
                           2017-07-17           MA709  02145283   14:52:31
                           2017-07-17           MA709  02145284   14:52:31
...                                               ...       ...        ...
                           2017-07-26           MA709  00974633   09:17:45
                           2017-07-26           MA709  00974634   09:17:45
                           2017-07-26           MA709  01013828   09:21:19
                           2017-07-26           MA709  01093725   09:29:56
                           2017-07-26           MA709  01112826   09:31:25
                           2017-07-26           MA709  01495649   10:36:08
                           2017-07-26           MA709  01496234   10:36:18
                           2017-07-26           MA709  01496235   10:36:18
                           2017-07-26           MA709  01496430   10:36:22
                           2017-07-26           MA709  00079694   21:04:13
                           2017-07-26           MA709  00098895   21:06:19
                           2017-07-26           MA709  00279646   21:37:52
                           2017-07-26           MA709  00279647   21:37:52
                           2017-07-26           MA709  00336213   21:51:18
                           2017-07-26           MA709  00343131   21:53:39
                           2017-07-26           MA709  00390590   22:06:55
                           2017-07-26           MA709  00390591   22:06:55
                           2017-07-26           MA709  00523197   22:32:24
                           2017-07-26           MA709  00524499   22:32:51
                           2017-07-26           MA709  00588105   22:52:01
                           2017-07-26           MA709  00593234   22:54:16
                           2017-07-26           MA709  00593264   22:54:17
                           2017-07-26           MA709  00668817   23:17:51
                           2017-07-26           MA709  00687077   23:22:36
                           2017-07-26           MA709  00724051   23:29:58
8               MA709      2017-08-03           MA709  00497387   23:04:19
                           2017-08-03           MA709  00502495   23:06:37
                           2017-08-03           MA709  00513093   23:10:03
                           2017-08-03           MA709  00513095   23:10:03
                           2017-08-03           MA709  00542044   23:23:56

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-17               0       2502.0     1
                           2017-07-17               0       2502.0     2
                           2017-07-17               0       2501.0     2
                           2017-07-17               0       2501.0     3
                           2017-07-17               1       2496.0     1
                           2017-07-17               1       2495.0     2
                           2017-07-17               1       2495.0     2
                           2017-07-17               0       2496.0     1
                           2017-07-17               0       2496.0     3
                           2017-07-17               0       2496.0     3
                           2017-07-17               1       2491.0     3
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2491.0     3
                           2017-07-17               1       2491.0     1
                           2017-07-17               0       2492.0     2
                           2017-07-17               0       2492.0     1
                           2017-07-17               0       2488.0     1
                           2017-07-17               0       2488.0     1
                           2017-07-17               0       2490.0     1
                           2017-07-17               0       2498.0     2
                           2017-07-17               0       2497.0     2
                           2017-07-17               0       2502.0     2
                           2017-07-17               0       2501.0     1
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2491.0     1
                           2017-07-17               1       2488.0     1
                           2017-07-17               1       2488.0     1
...                                               ...          ...   ...
                           2017-07-26               1       2476.0     2
                           2017-07-26               1       2476.0     3
                           2017-07-26               1       2470.0     3
                           2017-07-26               1       2466.0     2
                           2017-07-26               1       2467.0     2
                           2017-07-26               0       2451.0     3
                           2017-07-26               0       2451.0     2
                           2017-07-26               0       2451.0     1
                           2017-07-26               0       2451.0     1
                           2017-07-26               0       2491.0     4
                           2017-07-26               0       2490.0     1
                           2017-07-26               1       2484.0     4
                           2017-07-26               1       2484.0     1
                           2017-07-26               0       2486.0     3
                           2017-07-26               0       2486.0     2
                           2017-07-26               1       2482.0     3
                           2017-07-26               1       2482.0     2
                           2017-07-26               1       2468.0     3
                           2017-07-26               1       2469.0     1
                           2017-07-26               0       2472.0     2
                           2017-07-26               0       2471.0     1
                           2017-07-26               0       2471.0     1
                           2017-07-26               0       2476.0     2
                           2017-07-26               0       2478.0     2
                           2017-07-26               0       2479.0     1
8               MA709      2017-08-03               1       2435.0     2
                           2017-08-03               1       2436.0     2
                           2017-08-03               0       2439.0     1
                           2017-08-03               0       2439.0     1
                           2017-08-03               0       2440.0     2

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-17        25020.0           0   2.04
                           2017-07-17        50040.0           0   4.08
                           2017-07-17        50020.0           0   4.08
                           2017-07-17        75030.0           0   6.12
                           2017-07-17        24960.0           1   6.12
                           2017-07-17        49900.0           1  12.24
                           2017-07-17        49900.0           1  12.24
                           2017-07-17        24960.0           0   2.04
                           2017-07-17        74880.0           0   6.12
                           2017-07-17        74880.0           0   6.12
                           2017-07-17        74730.0           1  18.36
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        74730.0           1  18.36
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        49840.0           0   4.08
                           2017-07-17        24920.0           0   2.04
                           2017-07-17        24880.0           0   2.04
                           2017-07-17        24880.0           0   2.04
                           2017-07-17        24900.0           0   2.04
                           2017-07-17        49960.0           0   4.08
                           2017-07-17        49940.0           0   4.08
                           2017-07-17        50040.0           0   4.08
                           2017-07-17        25010.0           0   2.04
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        24910.0           1   6.12
                           2017-07-17        24880.0           1   6.12
                           2017-07-17        24880.0           1   6.12
...                                              ...         ...    ...
                           2017-07-26        49520.0           1  12.24
                           2017-07-26        74280.0           1  18.36
                           2017-07-26        74100.0           0   6.12
                           2017-07-26        49320.0           0   4.08
                           2017-07-26        49340.0           0   4.08
                           2017-07-26        73530.0           1  18.36
                           2017-07-26        49020.0           1  12.24
                           2017-07-26        24510.0           1   6.12
                           2017-07-26        24510.0           1   6.12
                           2017-07-26        99640.0           0   8.16
                           2017-07-26        24900.0           0   2.04
                           2017-07-26        99360.0           1  24.48
                           2017-07-26        24840.0           1   6.12
                           2017-07-26        74580.0           0   6.12
                           2017-07-26        49720.0           0   4.08
                           2017-07-26        74460.0           1  18.36
                           2017-07-26        49640.0           1  12.24
                           2017-07-26        74040.0           0   6.12
                           2017-07-26        24690.0           0   2.04
                           2017-07-26        49440.0           1  12.24
                           2017-07-26        24710.0           1   6.12
                           2017-07-26        24710.0           1   6.12
                           2017-07-26        49520.0           0   4.08
                           2017-07-26        49560.0           0   4.08
                           2017-07-26        24790.0           0   2.04
8               MA709      2017-08-03        48700.0           0   4.08
                           2017-08-03        48720.0           0   4.08
                           2017-08-03        24390.0           1   6.12
                           2017-08-03        24390.0           1   6.12
                           2017-08-03        48800.0           1  12.24

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               MA709      2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17             -60.0      2017-07-17
                           2017-07-17            -140.0      2017-07-17
                           2017-07-17            -120.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17            -300.0      2017-07-17
                           2017-07-17             -50.0      2017-07-17
                           2017-07-17            -150.0      2017-07-17
                           2017-07-17             -50.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17             -50.0      2017-07-17
                           2017-07-17             -50.0      2017-07-17
                           2017-07-17             -10.0      2017-07-17
                           2017-07-17             -10.0      2017-07-17
                           2017-07-17             -10.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
                           2017-07-17               0.0      2017-07-17
...                                                 ...             ...
                           2017-07-26            -160.0      2017-07-26
                           2017-07-26            -150.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26             570.0      2017-07-26
                           2017-07-26             300.0      2017-07-26
                           2017-07-26             160.0      2017-07-26
                           2017-07-26             160.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26            -280.0      2017-07-26
                           2017-07-26             -60.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26            -120.0      2017-07-26
                           2017-07-26             -80.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26             -80.0      2017-07-26
                           2017-07-26             -30.0      2017-07-26
                           2017-07-26             -20.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
8               MA709      2017-08-03               0.0      2017-08-03
                           2017-08-03               0.0      2017-08-03
                           2017-08-03             -40.0      2017-08-03
                           2017-08-03             -40.0      2017-08-03
                           2017-08-03             -80.0      2017-08-03

[347 rows x 11 columns]

In [19]:
df3[df3.instrument == 'MA709']

                                           instrument  order_no trade_time  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-26           MA709  00801137   09:02:09
                           2017-07-26           MA709  00825297   09:04:23
                           2017-07-26           MA709  00962920   09:16:36
                           2017-07-26           MA709  00974229   09:17:43
                           2017-07-26           MA709  00974231   09:17:43
                           2017-07-26           MA709  00974636   09:17:45
                           2017-07-26           MA709  00974637   09:17:45
                           2017-07-26           MA709  00974638   09:17:45
                           2017-07-26           MA709  01013830   09:21:19
                           2017-07-26           MA709  01093723   09:29:56
                           2017-07-26           MA709  01112830   09:31:25
                           2017-07-26           MA709  01495658   10:36:08
                           2017-07-26           MA709  01496237   10:36:18
                           2017-07-26           MA709  01496238   10:36:18
                           2017-07-26           MA709  01496436   10:36:22
8               MA709      2017-08-03           MA709  00497391   23:04:19
                           2017-08-03           MA709  00502504   23:06:37
                           2017-08-03           MA709  00513127   23:10:04
                           2017-08-03           MA709  00542055   23:23:56

                                            direction  order_price  lots  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-26               0       2484.0     3
                           2017-07-26               0       2484.0     2
                           2017-07-26               0       2481.0     3
                           2017-07-26               1       2477.0     1
                           2017-07-26               1       2477.0     1
                           2017-07-26               1       2476.0     1
                           2017-07-26               1       2476.0     2
                           2017-07-26               1       2476.0     3
                           2017-07-26               1       2470.0     3
                           2017-07-26               1       2466.0     2
                           2017-07-26               1       2467.0     2
                           2017-07-26               0       2451.0     3
                           2017-07-26               0       2451.0     2
                           2017-07-26               0       2451.0     1
                           2017-07-26               0       2451.0     1
8               MA709      2017-08-03               1       2435.0     2
                           2017-08-03               1       2436.0     2
                           2017-08-03               0       2439.0     2
                           2017-08-03               0       2440.0     2

                                            turnover  open_close    fee  \
real_trade_date instrument real_trade_date
7               MA709      2017-07-26        74520.0           0   6.18
                           2017-07-26        49680.0           0   4.12
                           2017-07-26        74430.0           0   6.18
                           2017-07-26        24770.0           1   6.18
                           2017-07-26        24770.0           1   6.18
                           2017-07-26        24760.0           1   6.18
                           2017-07-26        49520.0           1  12.36
                           2017-07-26        74280.0           1  18.54
                           2017-07-26        74100.0           0   6.18
                           2017-07-26        49320.0           0   4.12
                           2017-07-26        49340.0           0   4.12
                           2017-07-26        73530.0           1  18.54
                           2017-07-26        49020.0           1  12.36
                           2017-07-26        24510.0           1   6.18
                           2017-07-26        24510.0           1   6.18
8               MA709      2017-08-03        48700.0           0   4.12
                           2017-08-03        48720.0           0   4.12
                           2017-08-03        48780.0           1  12.36
                           2017-08-03        48800.0           1  12.36

                                            realized_pl real_trade_date
real_trade_date instrument real_trade_date
7               MA709      2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26             -70.0      2017-07-26
                           2017-07-26             -70.0      2017-07-26
                           2017-07-26             -80.0      2017-07-26
                           2017-07-26            -160.0      2017-07-26
                           2017-07-26            -150.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26               0.0      2017-07-26
                           2017-07-26             570.0      2017-07-26
                           2017-07-26             300.0      2017-07-26
                           2017-07-26             160.0      2017-07-26
                           2017-07-26             160.0      2017-07-26
8               MA709      2017-08-03               0.0      2017-08-03
                           2017-08-03               0.0      2017-08-03
                           2017-08-03             -80.0      2017-08-03
                           2017-08-03             -80.0      2017-08-03